import crypto from "node:crypto";
import http from "node:http";
import fs from "node:fs";
const planck = await import(process.env.NC11_PLANCK_PATH || "./planck.mjs");
const PITCH_ART_BASE64=fs.readFileSync(new URL("./assets/nc11-pitch-no-spawns.png",import.meta.url)).toString("base64");
const PAD_FREE_PITCH_ART_BASE64=fs.readFileSync(new URL("./assets/nc11-pitch-pad-free-v22.png",import.meta.url)).toString("base64");
const BOOST_PAD_HOUSING_BASE64=fs.readFileSync(new URL("./assets/official-boost-pad-housing.png",import.meta.url)).toString("base64");
const RANDOM_EVENT_IMAGE_BASE64=fs.readFileSync(new URL("./assets/random-event-overlay.png",import.meta.url)).toString("base64");
const RANDOM_EVENT_AUDIO_BASE64=fs.readFileSync(new URL("./assets/m-e-o-w.mp3",import.meta.url)).toString("base64");
const KICKOFF_BLUE_LAYOUT=Object.freeze([
  [33.75,18.75],[33.75,34.375],[33.75,50],[33.75,65.625],
  [45,21.875],[45,35.625],[45,49.375],[45,63.125],
  [56.25,28.125],[56.25,42.1875],[56.25,56.25],
].map(Object.freeze));

export const MODE = Object.freeze({
  ID: "11v11", BUILD: "0.1.44", PROTOCOL: 38, PLAYERS_PER_TEAM: 11, PLAYER_SLOTS: 22,
  SPECTATOR_CAPACITY: 32,
  ORIGINAL_FIELD_WIDTH: 100, ORIGINAL_FIELD_HEIGHT: 56.25, PITCH_ART_SOURCE_WIDTH: 4096,
  PITCH_SCALE: 1.5, NITROCLASH_MAP_SCALE: 1.5, PHYSICS_LENGTH_SCALE: 1, FIELD_WIDTH: 150, FIELD_HEIGHT: 84.375,
  FIELD_CORNER_RADIUS: 22.5, GOAL_OPENING_MULTIPLIER: 1.5, GOAL_OPENING: 14.0625, GOAL_DEPTH: 7.5,
  GOAL_MIN_Y: 35.15625, GOAL_MAX_Y: 49.21875,
  GOAL_ART_LINE_LEFT_X: 11.71875, GOAL_ART_LINE_RIGHT_X: 138.28125, GOAL_SCORING_INSET: 1,
  GOAL_LINE_LEFT_X: 12.71875, GOAL_LINE_RIGHT_X: 137.28125,
  PLAYER_SIZE_MULTIPLIER: 1, PLAYER_RADIUS: 0.6103515625,
  BALL_SIZE_MULTIPLIER: 1.09375, BALL_VISUAL_RATIO_TO_PLAYER: 1.75, BALL_RADIUS: 1.068115234375,
  BALL_RESTITUTION: 1, BALL_DENSITY: (0.005 / 1.2) * (0.9765625 / 1.068115234375) ** 2, BALL_FRICTION: 0.4,
  BALL_LINEAR_DAMPING: 0.25, BALL_ANGULAR_DAMPING: 0.2,
  BOUNDARY_RESTITUTION: 0.2, BOUNDARY_FRICTION: 0.6,
  PLAYER_DENSITY: 0.05, PLAYER_FRICTION: 0.4, PLAYER_RESTITUTION: 0.8,
  PHYSICS_REFERENCE_HZ: 60, PHYSICS_HZ: 60, SNAPSHOT_HZ: 60, CLIENT_INPUT_HZ: 120, MAX_PHYSICS_CATCHUP_STEPS: 4, REPLAY_HZ: 60,
  REGULATION_SECONDS: 600, MATCH_SECONDS: Math.max(30,Math.min(1200,Number(process.env.NC11_MATCH_SECONDS || 600))),
  COUNTDOWN_MS: 3000, GOAL_CELEBRATION_MS: 5000, GOAL_REPLAY_SECONDS: 6, POSTGAME_MS: Number(process.env.NC11_POSTGAME_MS || 60000),
  PENALTY_COUNTDOWN_MS: Number(process.env.NC11_PENALTY_COUNTDOWN_MS || 2500), PENALTY_SHOT_MS: Number(process.env.NC11_PENALTY_SHOT_MS || 10000), PENALTY_PAUSE_MS: Number(process.env.NC11_PENALTY_PAUSE_MS || 1800), PENALTY_INITIAL_ROUNDS: 5,
  PENALTY_BOX_LINE_X: 116.8945, PENALTY_TAKER_X: 98.75, PENALTY_BALL_X: 116.8945, PENALTY_GOALKEEPER_X: 136.5,
  PENALTY_TAKER_MAX_X: 116.2841484375, PENALTY_BALL_SPEED_MULTIPLIER: 1.4,
  PENALTY_EXIT_HYSTERESIS: 0.35, PENALTY_UNLIMITED_BOOST: true,
  PENALTY_GK_MIN_X: 135, PENALTY_GK_MAX_X: 139.25, PENALTY_GK_Y_MARGIN: 0.75,
  RECONNECT_MS: 60000, IDLE_MS: 45000, LOCAL_INACTIVITY_KICK_MS: 0, PUBLIC_INACTIVITY_KICK_MS: 20000,
  INACTIVITY_KICK_MS: Number(process.env.NC11_INACTIVITY_KICK_MS || 0), BOOST_RESPAWN_MS: 7000,
  ORIGINAL_PLAYER_RADIUS: 0.6103515625, ORIGINAL_PLAYER_MAX_SPEED: 10, ORIGINAL_PLAYER_ACCELERATION: 0.75,
  ORIGINAL_BALL_RADIUS: 0.9765625, ORIGINAL_PLAYER_DENSITY: 0.05, ORIGINAL_BALL_DENSITY: 0.005 / 1.2,
  SIZE_MASS_COMPENSATION: false, SIMILARITY_SCALED_PHYSICS: false,
  PACE_MULTIPLIER: 1.2, PLAYER_SPEED_MULTIPLIER: 1.2, MAX_SPEED: 12, ACCELERATION: 0.9,
  PLAYER_STEERING_CORRECTION: 0.5, PLAYER_TURN_RADIANS_PER_TICK: 0.1,
  PLAYER_OVERSPEED_RESISTANCE: 0.01, PLAYER_BRAKE_STRENGTH: 0.005, PLAYER_COAST_DRAG: 0.00075,
  BOOST_MULTIPLIER: 2, BOOSTED_TOP_SPEED: 24,
  BOOST_PAD_VISIBLE_TARGET_RATIO: 1.45, BOOST_PAD_ART_RADIUS: 1.25, BOOST_PAD_RADIUS: 1.25,
  STOCK_BOOST_PAD_COUNT: 14, EXTRA_BOOST_PAD_COUNT: 8, TOTAL_BOOST_PAD_COUNT: 22,
  BOOST_PAD_HOUSING_SOURCE_PIXELS: 128, BOOST_PAD_HOUSING_IMAGE_RADIUS: 2, BOOST_PAD_HOUSING_OPACITY: 1, BOOST_PAD_PICKUP_DISTANCE: 1.8,
  KICKOFF_BOOST: 50, KICKOFF_FORMATION: "4-4-3", KICKOFF_BLUE_LAYOUT,
  BOOST_PAD_REFILL: 50, BOOST_DRAIN_RATE_MULTIPLIER: 1.08, BOOST_DRAIN_PER_SECOND: 35.64, BOOST_DRAIN_PER_TICK: 0.594,
  BOOST_REGEN_MULTIPLIER: .8, BOOST_REGEN_PER_SECOND: .576, BOOST_REGEN_PER_TICK: .0096,
  DEFENSIVE_FIFTH_DEPTH: 30, DEFENSIVE_FIFTH_LIMIT: 5, CORNER_STALL_MS: Number(process.env.NC11_CORNER_STALL_MS||8000), WALL_STALL_MS: Number(process.env.NC11_WALL_STALL_MS||10000),
  CORNER_DETECT_X: 35, CORNER_DETECT_Y: 18, CORNER_CONTEST_RADIUS: 14, CORNER_STILL_SPEED: .35, CORNER_DETECT_GRACE_MS: 1000,
  CORNER_RADIUS: 21, CORNER_RESTART_MS: Number(process.env.NC11_CORNER_RESTART_MS||10000), CORNER_BALL_IMPULSE_MULTIPLIER: 2,
});

const DEFAULT_RULES=Object.freeze({matchSecondsNext:MODE.MATCH_SECONDS,ballCount:1,boostRegenPerSecond:MODE.BOOST_REGEN_PER_SECOND,unlimitedBoost:false,cornersEnabled:true,throwInsEnabled:true,cornerSensitivity:1,penaltyRounds:MODE.PENALTY_INITIAL_ROUNDS,boostPadRefill:MODE.BOOST_PAD_REFILL,playerSpeed:1,boostDeceleration:1,barrierEnabled:true,barrierLimit:MODE.DEFENSIVE_FIFTH_LIMIT,barrierDepth:MODE.DEFENSIVE_FIFTH_DEPTH,ballSpeed:1});
const ADMIN_PASSWORD=String(process.env.NC11_ADMIN_PASSWORD||"Chicken999!");
const adminFailures=new Map();
const ruleBounds={matchSecondsNext:[30,1200],ballCount:[1,5],boostRegenPerSecond:[0,12],cornerSensitivity:[.5,1.5],penaltyRounds:[1,22],boostPadRefill:[50,100],playerSpeed:[.5,3],boostDeceleration:[.25,4],barrierLimit:[1,11],barrierDepth:[15,60],ballSpeed:[.5,2]};
function sanitizedRules(current,changes){const next={...current};for(const [key,value] of Object.entries(changes||{})){if(!(key in DEFAULT_RULES))continue;if(typeof DEFAULT_RULES[key]==="boolean"){if(typeof value!=="boolean")throw Error(`${key} must be true or false`);next[key]=value;continue;}const n=Number(value),bounds=ruleBounds[key];if(!Number.isFinite(n)||n<bounds[0]||n>bounds[1])throw Error(`${key} must be between ${bounds[0]} and ${bounds[1]}`);next[key]=["matchSecondsNext","ballCount","penaltyRounds","boostPadRefill","barrierLimit"].includes(key)?Math.round(n):n;}return next;}
function publicRules(a){return {...a.rules,activeBalls:a.activeBallCount??1,matchSecondsCurrent:a.matchDurationSeconds??a.rules.matchSecondsNext};}

const scaleStockPad=([x,y])=>[+(x*MODE.NITROCLASH_MAP_SCALE).toFixed(4),+(y*MODE.NITROCLASH_MAP_SCALE).toFixed(4)];
const STOCK_BOOST_PADS = Object.freeze([
  [15.696192,47.998825],[15.696192,8.251172],[14.100928,28.125],
  [35.927097,34.41909],[35.927097,21.83091],
  [50,50.166016],[50,34.41909],[50,21.83091],[50,6.0839844],
  [64.0729,34.41909],[64.0729,21.83091],
  [84.303808,47.998825],[85.899072,28.125],[84.303808,8.251172],
].map(scaleStockPad));
const EXTRA_BOOST_PADS = Object.freeze([
  // Exact midpoints between the outer-corner and central lane groups.
  [38.717467,22.561562],[38.717467,61.813436],
  [111.282533,22.561562],[111.282533,61.813436],
  // A second goalkeeper pad sits inward from each original, with clear space.
  [31.5,42.1875],[118.5,42.1875],
  // Two additional pads fill the largest gaps on the middle line.
  [75,21.09375],[75,63.28125],
]);
export const BOOST_PAD_LAYOUT = Object.freeze([
  ...STOCK_BOOST_PADS,
  ...EXTRA_BOOST_PADS,
]);

// The stock NitroClash map is 100 x 56.25. Scaling every vertex by the same
// factor keeps the artwork, curved posts and physical wall hitboxes aligned.
const MAP_BORDERS = [
  [4.345703,23.4375,7.8125,23.4375,8.747321,23.065054,9.35389,22.033329,9.3727455,21.784855,9.375,15.625,9.419886,14.341579,9.554507,13.087652,9.77882,11.872826,10.092774,10.70671,10.496322,9.598909,10.989413,8.559029,11.572,7.5966754,12.244037,6.721461,13.005472,5.942987,13.856259,5.270861,14.796352,4.7146916,15.825697,4.284084,16.944252,3.988645,18.151962,3.8379812,18.762207,3.819908,34.470215,3.9541852,50.3125,3.880943],
  [95.6543,23.4375,92.1875,23.4375,91.252686,23.065052,90.64611,22.033329,90.62726,21.784855,90.625,15.625,90.58011,14.341579,90.44549,13.087652,90.221176,11.872826,89.90722,10.70671,89.50368,9.598909,89.01059,8.559029,88.427986,7.5966754,87.75597,6.721461,86.99453,5.942987,86.14373,5.270861,85.20364,4.7146916,84.17429,4.284084,83.05575,3.988645,81.84804,3.8379812,81.23779,3.819908,65.529785,3.9541852,49.6875,3.880943],
  [4.345703,32.8125,7.8125,32.8125,8.747321,33.18495,9.35389,34.21667,9.3727455,34.465145,9.375,40.625,9.419886,41.90842,9.554507,43.162342,9.77882,44.377174,10.0927725,45.543278,10.49632,46.651093,10.989413,47.690975,11.572,48.65332,12.244035,49.528538,13.005472,50.30701,13.856258,50.979137,14.796349,51.535305,15.825697,51.965916,16.94425,52.261356,18.151962,52.412018,18.762207,52.430096,34.470215,52.29581,50.3125,52.369057],
  [95.6543,32.8125,92.1875,32.8125,91.252686,33.18495,90.64611,34.21667,90.62726,34.465145,90.625,40.625,90.58011,41.90842,90.44549,43.162342,90.221176,44.377174,89.90721,45.543278,89.50368,46.651093,89.01059,47.690975,88.42799,48.65332,87.75596,49.528538,86.99452,50.30701,86.14374,50.979137,85.20364,51.535305,84.1743,51.965916,83.05575,52.261356,81.84804,52.412018,81.23779,52.430096,65.529785,52.29581,49.6875,52.369057],
  [4.375,23.4375,4.375,32.8125],
  [95.50781,23.4375,95.50781,32.8125],
];

const HOST = process.env.NC11_HOST || "127.0.0.1";
const PORT = Number(process.env.NC11_PORT || process.env.PORT || 8011);
const arenas = new Map(), parties = new Map(), reconnects = new Map();
let nextArenaId = 1;
const cleanName = v => String(v || "Player").replace(/[<>]/g, "").trim().slice(0, 16) || "Player";
const angleDifference=(from,to)=>{let d=(to-from)%(Math.PI*2);if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;return d;};
const now = () => Date.now();
const send = (c, value) => c.socket?.writable && c.socket.write(frame(Buffer.from(JSON.stringify(value)), 1));
const broadcast = (a, value) => {const packet=frame(Buffer.from(JSON.stringify(value)),1);for(const c of [...a.players.values(),...a.spectators])if(c.socket?.writable)c.socket.write(packet);};
const broadcastTeam = (a, team, value) => {const packet=frame(Buffer.from(JSON.stringify(value)),1);for(const [slot,c] of a.players)if(slot%2===team&&c.socket?.writable)c.socket.write(packet);};

function frame(payload, opcode = 1) {
  const n = payload.length;
  let h = n < 126 ? Buffer.from([0x80 | opcode, n]) : n <= 65535 ? Buffer.alloc(4) : Buffer.alloc(10);
  if (n >= 126 && n <= 65535) { h[0]=0x80|opcode;h[1]=126;h.writeUInt16BE(n,2); }
  if (n > 65535) { h[0]=0x80|opcode;h[1]=127;h.writeBigUInt64BE(BigInt(n),2); }
  return Buffer.concat([h,payload]);
}
function frames(c, chunk) {
  c.pending=Buffer.concat([c.pending,chunk]);const out=[];
  while(c.pending.length>=2){let n=c.pending[1]&127,o=2;if(n===126){if(c.pending.length<4)break;n=c.pending.readUInt16BE(2);o=4;}else if(n===127){if(c.pending.length<10)break;n=Number(c.pending.readBigUInt64BE(2));o=10;}const masked=!!(c.pending[1]&128),m=masked?4:0;if(c.pending.length<o+m+n)break;const key=masked?c.pending.subarray(o,o+4):null;o+=m;const p=Buffer.from(c.pending.subarray(o,o+n));if(key)for(let i=0;i<n;i++)p[i]^=key[i%4];out.push({op:c.pending[0]&15,p});c.pending=c.pending.subarray(o+n);}return out;
}
function kickoff(slot){const team=slot%2,row=Math.floor(slot/2),[blueX,y]=MODE.KICKOFF_BLUE_LAYOUT[row];return {x:team?MODE.FIELD_WIDTH-blueX:blueX,y,a:team?Math.PI:0};}
function world() {
  const physics=new planck.World({gravity:new planck.Vec2(0,0)}), wall=physics.createBody();
  const oldTop=23.4375,newTop=23.4375,edgeTop=3.819908,sourceHeight=MODE.ORIGINAL_FIELD_HEIGHT;
  const expandedGoalY=(y,chain)=>{if(chain<2)return edgeTop+(y-edgeTop)*(newTop-edgeTop)/(oldTop-edgeTop);if(chain<4)return sourceHeight-(edgeTop+(sourceHeight-y-edgeTop)*(newTop-edgeTop)/(oldTop-edgeTop));if(chain<6)return y<sourceHeight/2?newTop:sourceHeight-newTop;return y;};
  for(const [chain,points] of MAP_BORDERS.entries()){const vertices=[];for(let i=0;i<points.length;i+=2)vertices.push(new planck.Vec2(points[i]*MODE.NITROCLASH_MAP_SCALE,expandedGoalY(points[i+1],chain)*MODE.NITROCLASH_MAP_SCALE));wall.createFixture(new planck.Chain(vertices),{restitution:MODE.BOUNDARY_RESTITUTION,friction:MODE.BOUNDARY_FRICTION,filterCategoryBits:0x0001,filterMaskBits:0x0006});}
  const players=Array.from({length:MODE.PLAYER_SLOTS},(_,slot)=>{const k=kickoff(slot),body=physics.createDynamicBody({position:new planck.Vec2(k.x,k.y),angle:k.a,angularDamping:0.5});body.setUserData({type:"player",slot});const fixture=body.createFixture(new planck.Circle(MODE.PLAYER_RADIUS),{density:MODE.PLAYER_DENSITY,friction:MODE.PLAYER_FRICTION,restitution:MODE.PLAYER_RESTITUTION,filterCategoryBits:0x0002,filterMaskBits:0x0007});body.setActive(false);return {slot,body,fixture,name:"",energy:100,input:{x:0,y:0,boost:false,brake:false}};});
  const balls=Array.from({length:5},(_,index)=>{const body=physics.createDynamicBody({position:new planck.Vec2(MODE.FIELD_WIDTH/2,MODE.FIELD_HEIGHT/2),linearDamping:MODE.BALL_LINEAR_DAMPING,angularDamping:MODE.BALL_ANGULAR_DAMPING});body.setUserData({type:"ball",index});body.createFixture(new planck.Circle(MODE.BALL_RADIUS),{density:MODE.BALL_DENSITY,friction:MODE.BALL_FRICTION,restitution:MODE.BALL_RESTITUTION,filterCategoryBits:0x0004,filterMaskBits:0x0007});body.setActive(index===0);return body;});
  return {physics,players,ball:balls[0],balls,boosts:BOOST_PAD_LAYOUT.map(([x,y])=>({x,y,active:true,at:0})),score:[0,0],tick:0,overtime:false};
}
function setBallLightness(a){for(const ball of a.world.balls){const fixture=ball.getFixtureList();fixture.setDensity(MODE.BALL_DENSITY/a.rules.ballSpeed);ball.resetMassData();}}
function freeBallSpawn(a){const occupied=[...a.world.balls.slice(0,a.activeBallCount).map(ball=>ball.getPosition()),...[...a.players.keys()].filter(slot=>a.world.players[slot].body.isActive()).map(slot=>a.world.players[slot].body.getPosition())];let best=null,bestScore=-Infinity;for(let x=45;x<=105;x+=5)for(let y=20;y<=65;y+=5){const clearance=Math.min(...occupied.map(q=>Math.hypot(q.x-x,q.y-y))),score=clearance-.025*Math.hypot(x-MODE.FIELD_WIDTH/2,y-MODE.FIELD_HEIGHT/2);if(score>bestScore){bestScore=score;best={x,y};}}return best;}
function syncActiveBalls(a){const desired=a.rules.ballCount;if(!["playing","countdown"].includes(a.phase)||a.shootout)return;while(a.activeBallCount<desired){const index=a.activeBallCount,pos=freeBallSpawn(a),ball=a.world.balls[index];ball.setTransform(new planck.Vec2(pos.x,pos.y),0);ball.setLinearVelocity(new planck.Vec2());ball.setAngularVelocity(0);ball.setActive(true);a.ballTouches[index]=null;a.ballTouchHistory[index]=[];a.ballContactSlots[index]=new Set();a.ballStalls[index]={cornerAt:0,lastValidAt:0,wallAt:0};a.activeBallCount++;}while(a.activeBallCount>desired){const index=--a.activeBallCount;if(a.setPiece?.ballIndex===index){if(a.setPiece.type==="corner")releaseCornerTaker(a,a.setPiece);a.setPiece=null;broadcast(a,{t:"restart",active:false});}a.world.balls[index].setActive(false);a.ballTouches[index]=null;a.ballTouchHistory[index]=[];a.ballContactSlots[index]=new Set();a.ballStalls[index]={cornerAt:0,lastValidAt:0,wallAt:0};}}
function makeArena(kind="public",party=null){const a={id:nextArenaId++,kind,party,world:world(),players:new Map(),spectators:new Set(),phase:"waiting",phaseUntil:0,startedAt:0,clockRemainingMs:MODE.MATCH_SECONDS*1000,clockLastAt:0,lastUsed:now(),lastReplayAt:0,replay:[],events:[],votes:new Map(),shootout:null,lastBallTouchSlot:null,touchHistory:[],ballTouches:Array(5).fill(null),ballTouchHistory:Array.from({length:5},()=>[]),ballContactSlots:Array.from({length:5},()=>new Set()),ballStalls:Array.from({length:5},()=>({cornerAt:0,lastValidAt:0,wallAt:0})),activeBallCount:1,matchDurationSeconds:MODE.MATCH_SECONDS,rules:{...DEFAULT_RULES},pendingGoalReplay:null,meowEnabled:true,quickChatSet:"custom",randomEventEligible:false,randomEventAt:0,randomEventPlayed:false};arenas.set(a.id,a);if(party)parties.set(party,a);return a;}
const openSlots = a => Array.from({length:MODE.PLAYER_SLOTS},(_,i)=>i).filter(i=>!a.players.has(i));
function teamCounts(a){const counts=[0,0];for(const slot of a.players.keys())counts[slot%2]++;return counts;}
function balanceState(a){const counts=teamCounts(a),difference=counts[0]-counts[1];return Math.abs(difference)>=2?{counts,fromTeam:difference>0?0:1,toTeam:difference>0?1:0,needed:Math.floor(Math.abs(difference)/2)}:{counts,fromTeam:null,toTeam:null,needed:0};}
function broadcastBalance(a){const status=balanceState(a);broadcast(a,{t:"balance",...status});return status;}
function pickSlot(a){const free=openSlots(a),counts=teamCounts(a),team=counts[0]<=counts[1]?0:1;return free.find(i=>i%2===team)??free[0]??null;}
function savedSlotKeepsBalance(a,slot){const counts=teamCounts(a);counts[slot%2]++;return Math.abs(counts[0]-counts[1])<=1;}
function publicArena(target){if(target){const a=arenas.get(target);if(a?.kind==="public"&&a.phase!=="retired"&&openSlots(a).length)return a;return null;}return [...arenas.values()].find(a=>a.kind==="public"&&a.phase!=="retired"&&openSlots(a).length)||makeArena();}
function activate(a,c,slot){c.arena=a;c.slot=slot;c.role="player";a.players.set(slot,c);a.spectators.delete(c);const p=a.world.players[slot],k=kickoff(slot);p.fixture.setFilterMaskBits(0x0007);p.name=c.name;p.body.setActive(true);p.body.setTransform(new planck.Vec2(k.x,k.y),k.a);p.body.setLinearVelocity(new planck.Vec2());p.body.setAngularVelocity(0);p.energy=MODE.KICKOFF_BOOST;c.lastMovementAt=now();c.lastMovementX=k.x;c.lastMovementY=k.y;a.lastUsed=now();}
function park(a,slot){const p=a.world.players[slot];p.fixture.setFilterMaskBits(0x0007);p.name="";p.body.setLinearVelocity(new planck.Vec2());p.body.setAngularVelocity(0);p.body.setActive(false);p.body.setTransform(new planck.Vec2(-100,-100),0);}
function resetPositions(a){for(const [slot] of a.players){const p=a.world.players[slot],k=kickoff(slot);p.fixture.setFilterMaskBits(0x0007);p.body.setTransform(new planck.Vec2(k.x,k.y),k.a);p.body.setLinearVelocity(new planck.Vec2());p.body.setAngularVelocity(0);p.energy=MODE.KICKOFF_BOOST;}for(const pad of a.world.boosts){pad.active=true;pad.at=0;}a.activeBallCount=a.rules.ballCount;const offsets=[[0,0],[-3,0],[3,0],[0,-3],[0,3]];for(let index=0;index<a.world.balls.length;index++){const ball=a.world.balls[index],offset=offsets[index];ball.setActive(index<a.activeBallCount);ball.setTransform(new planck.Vec2(MODE.FIELD_WIDTH/2+offset[0],MODE.FIELD_HEIGHT/2+offset[1]),0);ball.setLinearVelocity(new planck.Vec2());ball.setAngularVelocity(0);}a.ballTouches=Array(5).fill(null);a.ballTouchHistory=Array.from({length:5},()=>[]);a.ballContactSlots=Array.from({length:5},()=>new Set());a.ballStalls=Array.from({length:5},()=>({cornerAt:0,lastValidAt:0,wallAt:0}));a.lastBallTouchSlot=null;a.touchHistory=[];a.pendingGoalReplay=null;a.setPiece=null;broadcast(a,{t:"rules",rules:publicRules(a)});}
function begin(a){a.phase="countdown";a.phaseUntil=now()+MODE.COUNTDOWN_MS;a.startedAt=a.phaseUntil;a.matchDurationSeconds=a.rules.matchSecondsNext;a.clockRemainingMs=a.matchDurationSeconds*1000;a.clockLastAt=a.phaseUntil;a.lastReplayAt=0;a.world.score=[0,0];a.world.overtime=false;a.shootout=null;a.replay=[];a.events=[];a.randomEventEligible=Math.random()<.5;a.randomEventAt=a.startedAt+5000+Math.random()*Math.max(0,a.matchDurationSeconds*1000-10000);a.randomEventPlayed=false;setBallLightness(a);resetPositions(a);broadcast(a,{t:"notice",text:"Kickoff"});broadcastBalance(a);}
function ballSnapshot(ball){const p=ball.getPosition(),v=ball.getLinearVelocity();return [+p.x.toFixed(3),+p.y.toFixed(3),+v.x.toFixed(2),+v.y.toFixed(2),+ball.getAngle().toFixed(3),+ball.getAngularVelocity().toFixed(3)];}
function snapshot(a){const w=a.world,n=now(),penalty=a.shootout?{score:[...a.shootout.score],attempts:[...a.shootout.attempts],results:a.shootout.results.map(x=>[...x]),shootingTeam:a.shootout.shootingTeam,shooterSlot:a.shootout.shooterSlot,gkSlot:a.shootout.gkSlot,shotMs:a.phase==="penalty"?Math.max(0,a.phaseUntil-n):0}:null,balls=w.balls.slice(0,a.activeBallCount).map(ballSnapshot);return {t:"state",arena:a.id,tick:w.tick,simTime:w.tick*1000/MODE.PHYSICS_HZ,serverTime:n,phase:a.phase,countdownMs:a.phase==="countdown"||a.phase==="penaltyCountdown"?Math.max(0,a.phaseUntil-n):0,score:w.score,clock:a.phase==="penalty"?Math.max(0,Math.ceil((a.phaseUntil-n)/1000)):Math.max(0,Math.ceil(a.clockRemainingMs/1000)),overtime:false,penalty,p:w.players.map(p=>{const q=p.body.getPosition(),v=p.body.getLinearVelocity(),c=a.players.get(p.slot);return [p.slot,+q.x.toFixed(3),+q.y.toFixed(3),+p.body.getAngle().toFixed(3),+v.x.toFixed(2),+v.y.toFixed(2),Math.round(p.energy),p.body.isActive()?1:0,c?.ping??0,p.input.boost&&Math.hypot(p.input.x,p.input.y)>0&&(p.input.brake||a.rules.unlimitedBoost||p.energy>=MODE.BOOST_DRAIN_PER_TICK)?1:0];}),b:balls[0],balls,pads:w.boosts.map(x=>x.active?1:0),spaces:openSlots(a).length};}
function score(a,team,ballIndex=0){a.world.score[team]++;const history=a.ballTouchHistory[ballIndex],lastTouchSlot=a.ballTouches[ballIndex],scorerSlot=lastTouchSlot!=null&&lastTouchSlot%2===team?lastTouchSlot:null,scorerIndex=history.findLastIndex(t=>t.slot===scorerSlot),assist=[...history.slice(0,Math.max(0,scorerIndex))].reverse().find(t=>t.slot!==scorerSlot&&t.slot%2===team),assistSlot=assist?.slot??null,lastTouch=scorerIndex>=0?history[scorerIndex]:null,speedKmh=Math.max(0,Math.ceil((lastTouch?.speed||a.world.balls[ballIndex].getLinearVelocity().length())*5)),cutoff=Math.max(0,(a.replay.at(-1)?.replayMs||0)-MODE.GOAL_REPLAY_SECONDS*1000),recent=a.replay.filter(frame=>frame.replayMs>=cutoff),frames=recent.filter((_,i)=>i%6===0||i===recent.length-1),clipStartMs=frames[0]?.replayMs??0,clipEndMs=frames.at(-1)?.replayMs??clipStartMs;a.events.push({at:a.world.tick,replayMs:clipEndMs,type:"goal",team,ballIndex,scorerSlot,assistSlot,speedKmh,score:[...a.world.score]});a.phase="goalCelebration";a.phaseUntil=now()+MODE.GOAL_CELEBRATION_MS;a.pendingGoalReplay={t:"goalReplay",team,ballIndex,scorerSlot,durationMs:MODE.GOAL_REPLAY_SECONDS*1000,clipStartMs,clipEndMs,frames};for(const [slot] of a.players)if(slot%2===team)a.world.players[slot].energy=100;broadcast(a,{t:"goal",team,ballIndex,scorerSlot,assistSlot,speedKmh,score:a.world.score,celebrationMs:MODE.GOAL_CELEBRATION_MS});}
function finish(a){a.phase="ended";a.phaseUntil=now()+MODE.POSTGAME_MS;a.votes.clear();broadcast(a,{t:"ended",score:a.world.score,shootout:a.shootout?{score:[...a.shootout.score],results:a.shootout.results.map(x=>[...x]),winner:a.shootout.winner}:null,replayReady:true,deadlineMs:MODE.POSTGAME_MS});}
function restart(a,shuffle=false){const rows=[...a.players.entries()].map(([slot,c])=>({slot,c}));a.phase="waiting";a.votes.clear();a.shootout=null;a.world=world();a.lastBallTouchSlot=null;a.touchHistory=[];a.pendingGoalReplay=null;a.players.clear();if(shuffle){for(let i=rows.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[rows[i],rows[j]]=[rows[j],rows[i]];}rows.forEach((row,i)=>activate(a,row.c,i));}else for(const row of rows)activate(a,row.c,row.slot);broadcast(a,{t:"roster",names:[...a.players].map(([slot,c])=>[slot,c.name]),spaces:openSlots(a).length});begin(a);}
function switchTeam(a,c){if(c.role!=="player"||c.slot==null)return false;const status=balanceState(a),sourceSlot=c.slot;if(!status.needed||sourceSlot%2!==status.fromTeam)return false;const targetSlot=openSlots(a).find(slot=>slot%2===status.toTeam);if(targetSlot==null)return false;const source=a.world.players[sourceSlot],target=a.world.players[targetSlot],position=source.body.getPosition(),velocity=source.body.getLinearVelocity(),angle=source.body.getAngle(),angularVelocity=source.body.getAngularVelocity(),energy=source.energy,input={...source.input};a.players.delete(sourceSlot);park(a,sourceSlot);c.slot=targetSlot;a.players.set(targetSlot,c);target.name=c.name;target.energy=energy;target.input=input;target.body.setActive(true);target.body.setTransform(new planck.Vec2(position.x,position.y),angle);target.body.setLinearVelocity(new planck.Vec2(velocity.x,velocity.y));target.body.setAngularVelocity(angularVelocity);send(c,{t:"slot",slot:targetSlot,reason:"Team balanced"});broadcast(a,{t:"roster",names:[...a.players].map(([slot,client])=>[slot,client.name]),spaces:openSlots(a).length});broadcastBalance(a);return true;}
function penaltyPlayers(a,team){const eligible=a.shootout?.eligibleSlots||[...a.players.keys()];return eligible.filter(slot=>a.players.has(slot)&&slot%2===team);}
function choosePenaltyPlayer(a,team,role){const s=a.shootout,queue=s.penaltyQueues[role][team],eligible=penaltyPlayers(a,team);while(queue.length&&!eligible.includes(queue[0]))queue.shift();if(!queue.length)queue.push(...eligible);return queue.shift()??null;}
function preparePenaltyActors(a){const s=a.shootout,centreY=MODE.FIELD_HEIGHT/2;s.enteredBox=false;s.ballTouched=false;s.shooterTouching=false;for(const [slot] of a.players){const p=a.world.players[slot];p.input={x:0,y:0,boost:false,brake:false};p.body.setLinearVelocity(new planck.Vec2());p.body.setAngularVelocity(0);p.body.setActive(slot===s.shooterSlot||slot===s.gkSlot);}const shooter=a.world.players[s.shooterSlot],keeper=a.world.players[s.gkSlot];shooter.energy=100;shooter.body.setTransform(new planck.Vec2(MODE.PENALTY_TAKER_X,centreY),0);keeper.energy=100;keeper.body.setTransform(new planck.Vec2(MODE.PENALTY_GOALKEEPER_X,centreY),Math.PI);a.world.ball.setTransform(new planck.Vec2(MODE.PENALTY_BALL_X,centreY),0);a.world.ball.setLinearVelocity(new planck.Vec2());a.world.ball.setAngularVelocity(0);}
function penaltyWinner(s){const [a0,a1]=s.attempts,[s0,s1]=s.score,R=s.initialRounds;if(a0<=R&&a1<=R){if(s0>s1+Math.max(0,R-a1))return 0;if(s1>s0+Math.max(0,R-a0))return 1;}if(a0>=R&&a1>=R&&a0===a1&&s0!==s1)return s0>s1?0:1;return null;}
function startPenaltyShot(a){const s=a.shootout,team=s.shotIndex%2,other=1-team,shooter=choosePenaltyPlayer(a,team,"shooter"),keeper=choosePenaltyPlayer(a,other,"keeper");if(shooter==null||keeper==null){s.winner=shooter==null?other:team;finish(a);return;}s.shootingTeam=team;s.shooterSlot=shooter;s.gkSlot=keeper;s.lastShooter[team]=shooter;s.lastKeeper[other]=keeper;preparePenaltyActors(a);a.phase="penaltyCountdown";a.phaseUntil=now()+MODE.PENALTY_COUNTDOWN_MS;broadcast(a,{t:"penaltyStart",team,shooterSlot:shooter,gkSlot:keeper,score:[...s.score],attempts:[...s.attempts],countdownMs:MODE.PENALTY_COUNTDOWN_MS});}
function beginShootout(a){if(a.setPiece?.type==="corner")releaseCornerTaker(a,a.setPiece);a.setPiece=null;for(const ball of a.world.balls.slice(1))ball.setActive(false);a.activeBallCount=1;broadcast(a,{t:"rules",rules:publicRules(a)});const eligibleSlots=[...a.players.keys()].sort((x,y)=>x-y);a.shootout={score:[0,0],attempts:[0,0],results:[[],[]],shotIndex:0,shootingTeam:0,shooterSlot:null,gkSlot:null,lastShooter:[null,null],lastKeeper:[null,null],eligibleSlots,penaltyQueues:{shooter:[eligibleSlots.filter(x=>x%2===0),eligibleSlots.filter(x=>x%2===1)],keeper:[eligibleSlots.filter(x=>x%2===0),eligibleSlots.filter(x=>x%2===1)]},initialRounds:a.rules.penaltyRounds,enteredBox:false,ballTouched:false,shooterTouching:false,winner:null};broadcast(a,{t:"notice",text:"Penalty shootout"});startPenaltyShot(a);}
function resolvePenalty(a,goal){const s=a.shootout;if(!s||a.phase!=="penalty")return;const team=s.shootingTeam;s.attempts[team]++;s.results[team].push(!!goal);if(goal)s.score[team]++;a.events.push({at:a.world.tick,type:"penalty",team,goal:!!goal,score:[...s.score],attempts:[...s.attempts]});broadcast(a,{t:"penaltyResult",team,goal:!!goal,score:[...s.score],attempts:[...s.attempts],results:s.results.map(x=>[...x])});const winner=penaltyWinner(s);if(winner!=null){s.winner=winner;finish(a);return;}s.shotIndex++;a.phase="penaltyPause";a.phaseUntil=now()+MODE.PENALTY_PAUSE_MS;}
function finalizeRematch(a){for(const [slot,c] of [...a.players])if(!a.votes.has(c.id)){a.players.delete(slot);park(a,slot);send(c,{t:"returnHome",reason:"Rematch choice timed out"});c.arena=null;c.slot=null;setTimeout(()=>c.socket.end(),100);}if(!a.players.size)return;let same=0,shuffle=0;for(const c of a.players.values())(a.votes.get(c.id)==="shuffle"?shuffle++:same++);const useShuffle=shuffle>same;broadcast(a,{t:"rematchResult",choice:useShuffle?"shuffle":"same",same,shuffle});restart(a,useShuffle);}
function enforceDefensiveFifths(a){if(a.phase!=="playing"||!a.rules.barrierEnabled)return;const w=a.world,depth=a.rules.barrierDepth,limit=a.rules.barrierLimit,orders=a.defensiveOrders??=[new Map(),new Map()];a.defensiveOrderSeq??=0;for(const team of [0,1]){const inside=[];for(const [slot] of a.players){if(slot%2!==team)continue;const p=w.players[slot],q=p.body.getPosition(),isInside=team===0?q.x<=depth:q.x>=MODE.FIELD_WIDTH-depth;if(isInside){if(!orders[team].has(slot))orders[team].set(slot,++a.defensiveOrderSeq);inside.push({slot,p,q,order:orders[team].get(slot)});}else orders[team].delete(slot);}inside.sort((x,y)=>x.order-y.order);for(const member of inside.slice(limit)){orders[team].delete(member.slot);const x=team===0?depth+.03:MODE.FIELD_WIDTH-depth-.03,v=member.p.body.getLinearVelocity();member.p.body.setTransform(new planck.Vec2(x,member.q.y),member.p.body.getAngle());member.p.body.setLinearVelocity(new planck.Vec2(team===0?Math.max(.02,v.x):Math.min(-.02,v.x),v.y));}}}
function nearestTeamSlot(a,team,x,y){let best=null,distance=Infinity;for(const [slot] of a.players){if(slot%2!==team)continue;const q=a.world.players[slot].body.getPosition(),d=Math.hypot(q.x-x,q.y-y);if(d<distance){best=slot;distance=d;}}return best;}
function enforceGoalKickClearance(a){const s=a.setPiece;if(s?.type!=="goalKick")return;const boundary=s.team===0?MODE.DEFENSIVE_FIFTH_DEPTH+.5:MODE.FIELD_WIDTH-MODE.DEFENSIVE_FIFTH_DEPTH-.5;for(const [slot] of a.players){if(slot%2===s.team)continue;const p=a.world.players[slot],q=p.body.getPosition(),inside=s.team===0?q.x<boundary:q.x>boundary;if(!inside)continue;p.body.setTransform(new planck.Vec2(boundary,q.y),p.body.getAngle());const v=p.body.getLinearVelocity();p.body.setLinearVelocity(new planck.Vec2(s.team===0?Math.max(0,v.x):Math.min(0,v.x),v.y));}}
function releaseCornerTaker(a,s,returnInside=true){if(s?.type!=="corner"||s.taker==null)return;const p=a.world.players[s.taker];if(!p)return;p.fixture.setFilterMaskBits(0x0007);if(!returnInside)return;const q=p.body.getPosition(),dx=MODE.FIELD_WIDTH/2-s.x,dy=MODE.FIELD_HEIGHT/2-s.y,l=Math.hypot(dx,dy)||1,ux=dx/l,uy=dy/l,inward=(q.x-s.x)*ux+(q.y-s.y)*uy;if(q.x<0||q.x>MODE.FIELD_WIDTH||q.y<0||q.y>MODE.FIELD_HEIGHT||inward<MODE.PLAYER_RADIUS+1){const safe=MODE.PLAYER_RADIUS+2.25,v=p.body.getLinearVelocity(),outward=Math.min(0,v.x*ux+v.y*uy);p.body.setTransform(new planck.Vec2(s.x+ux*safe,s.y+uy*safe),p.body.getAngle());p.body.setLinearVelocity(new planck.Vec2(v.x-ux*outward,v.y-uy*outward));}}
function placeCornerTaker(a,s){if(s?.type!=="corner")return;const slot=nearestTeamSlot(a,s.team,s.x,s.y);s.taker=slot;if(slot==null)return;const p=a.world.players[slot],dx=MODE.FIELD_WIDTH/2-s.x,dy=MODE.FIELD_HEIGHT/2-s.y,l=Math.hypot(dx,dy)||1,ux=dx/l,uy=dy/l,run=7;p.fixture.setFilterMaskBits(0x0006);p.body.setTransform(new planck.Vec2(s.x-ux*run,s.y-uy*run),Math.atan2(uy,ux));p.body.setLinearVelocity(new planck.Vec2());}
function startSetPiece(a,type,team,x,y,ballIndex=0){const w=a.world,n=now(),ball=w.balls[ballIndex];if(a.setPiece?.type==="corner")releaseCornerTaker(a,a.setPiece);if(type==="corner"){a.restartCornerX=x;a.restartCornerY=y;}a.setPiece={type,team,x,y,ballIndex,taker:null,deadline:n+MODE.CORNER_RESTART_MS,ballMoved:false};ball.setTransform(new planck.Vec2(x,y),0);ball.setLinearVelocity(new planck.Vec2());ball.setAngularVelocity(0);if(type==="corner")placeCornerTaker(a,a.setPiece);else{const taker=nearestTeamSlot(a,team,x,y);a.setPiece.taker=taker;if(taker!=null){const p=w.players[taker],dx=MODE.FIELD_WIDTH/2-x,dy=MODE.FIELD_HEIGHT/2-y,l=Math.hypot(dx,dy)||1,run=7,runX=x+dx/l*run,runY=y+dy/l*run;p.body.setTransform(new planck.Vec2(runX,runY),Math.atan2(y-runY,x-runX));p.body.setLinearVelocity(new planck.Vec2());}}if(type==="goalKick")for(const [slot] of a.players){if(slot%2===team)continue;const p=w.players[slot],q=p.body.getPosition(),boundary=team===0?MODE.DEFENSIVE_FIFTH_DEPTH+.5:MODE.FIELD_WIDTH-MODE.DEFENSIVE_FIFTH_DEPTH-.5;if(team===0&&q.x<boundary)p.body.setTransform(new planck.Vec2(boundary,q.y),p.body.getAngle());if(team===1&&q.x>boundary)p.body.setTransform(new planck.Vec2(boundary,q.y),p.body.getAngle());}const taker=a.setPiece.taker,takerName=taker==null?"":` — ${a.players.get(taker)?.name||`Player ${taker+1}`} taking`;broadcast(a,{t:"restart",active:true,type,team,x,y,ballIndex,radius:MODE.CORNER_RADIUS,taker,deadlineMs:MODE.CORNER_RESTART_MS});broadcast(a,{t:"notice",text:`${team?"Red":"Blue"} ${type==="corner"?"corner kick":"goal kick"}${takerName}`});}
function manageSetPiece(a,n){const s=a.setPiece;if(!s)return;const w=a.world;a.startedAt+=1000/MODE.PHYSICS_HZ;w.tick=Math.max(0,w.tick-1);if(s.type==="corner"&&!a.players.has(s.taker)){releaseCornerTaker(a,s,false);placeCornerTaker(a,s);broadcast(a,{t:"restart",active:true,type:s.type,team:s.team,x:s.x,y:s.y,ballIndex:s.ballIndex,radius:MODE.CORNER_RADIUS,taker:s.taker,deadlineMs:Math.max(0,s.deadline-n)});}if(s.type==="corner")for(const [slot] of a.players){if(slot%2===s.team)continue;const p=w.players[slot],q=p.body.getPosition(),dx=q.x-s.x,dy=q.y-s.y,d=Math.hypot(dx,dy),clear=MODE.CORNER_RADIUS+MODE.PLAYER_RADIUS+.25;if(d<clear){const cx=MODE.FIELD_WIDTH/2-s.x,cy=MODE.FIELD_HEIGHT/2-s.y,cl=Math.hypot(cx,cy)||1,ux=cx/cl,uy=cy/cl,dot=dx*ux+dy*uy,t=-dot+Math.sqrt(Math.max(0,dot*dot+clear*clear-d*d));p.body.setTransform(new planck.Vec2(q.x+ux*t,q.y+uy*t),p.body.getAngle());p.body.setLinearVelocity(new planck.Vec2());}}if(n>=s.deadline){if(s.type==="corner"){const defending=1-s.team,x=defending===0?MODE.GOAL_LINE_LEFT_X+4:MODE.GOAL_LINE_RIGHT_X-4;startSetPiece(a,"goalKick",defending,x,MODE.FIELD_HEIGHT/2,s.ballIndex);}else{const attacking=1-s.team,x=a.restartCornerX??(s.team===0?25.5:MODE.FIELD_WIDTH-25.5),y=a.restartCornerY??MODE.FIELD_HEIGHT/2;startSetPiece(a,"corner",attacking,x,y,s.ballIndex);}}}
function finishSetPieceAfterStep(a){const s=a.setPiece;if(!s)return;const ball=a.world.balls[s.ballIndex],v=ball.getLinearVelocity(),speed=v.length();if(speed<.12)return;if(s.type==="corner"&&!s.ballMoved){s.ballMoved=true;v.mul(MODE.CORNER_BALL_IMPULSE_MULTIPLIER);ball.setLinearVelocity(v);releaseCornerTaker(a,s);}a.setPiece=null;broadcast(a,{t:"restart",active:false});broadcast(a,{t:"notice",text:"Ball in play"});}
function updateStallSafety(a,n){
  if(a.phase!=="playing"||a.setPiece)return;
  const w=a.world,r=a.rules,sensitivity=r.cornerSensitivity;
  for(let index=0;index<a.activeBallCount;index++){
    const ball=w.balls[index],b=ball.getPosition(),speed=ball.getLinearVelocity().length(),stall=a.ballStalls[index];
    const left=b.x<MODE.CORNER_DETECT_X*sensitivity,right=b.x>MODE.FIELD_WIDTH-MODE.CORNER_DETECT_X*sensitivity;
    const top=b.y<MODE.CORNER_DETECT_Y*sensitivity,bottom=b.y>MODE.FIELD_HEIGHT-MODE.CORNER_DETECT_Y*sensitivity;
    const nearCorner=(left||right)&&(top||bottom),nearWall=b.y<4||b.y>MODE.FIELD_HEIGHT-4||b.x<15||b.x>MODE.FIELD_WIDTH-15,near=[0,0];
    for(const [slot] of a.players){const q=w.players[slot].body.getPosition();if(Math.hypot(q.x-b.x,q.y-b.y)<MODE.CORNER_CONTEST_RADIUS*sensitivity)near[slot%2]++;}
    const cornerContest=r.cornersEnabled&&nearCorner&&near[0]&&near[1];
    if(cornerContest&&speed<MODE.CORNER_STILL_SPEED*sensitivity){if(!stall.cornerAt)stall.cornerAt=n;stall.lastValidAt=n;}
    else if(!cornerContest||!stall.lastValidAt||n-stall.lastValidAt>MODE.CORNER_DETECT_GRACE_MS){stall.cornerAt=0;stall.lastValidAt=0;}
    if(stall.cornerAt&&n-stall.cornerAt>=MODE.CORNER_STALL_MS){const attacking=left?1:0;stall.cornerAt=0;stall.lastValidAt=0;startSetPiece(a,"corner",attacking,b.x,b.y,index);return;}
    if(r.throwInsEnabled&&(!nearCorner||!r.cornersEnabled)&&nearWall&&speed<.08&&near[0]&&near[1]){if(!stall.wallAt)stall.wallAt=n;}else stall.wallAt=0;
    if(stall.wallAt&&n-stall.wallAt>=MODE.WALL_STALL_MS){stall.wallAt=0;const dx=MODE.FIELD_WIDTH/2-b.x,dy=MODE.FIELD_HEIGHT/2-b.y,l=Math.hypot(dx,dy)||1;ball.applyLinearImpulse(new planck.Vec2(dx/l*.8+(Math.random()-.5)*.3,dy/l*.8+(Math.random()-.5)*.3),b,true);for(const [slot] of a.players){const p=w.players[slot],q=p.body.getPosition(),px=q.x-b.x,py=q.y-b.y,d=Math.hypot(px,py);if(d<3&&d>.01)p.body.applyLinearImpulse(new planck.Vec2(px/d*.35,py/d*.35),q,true);}broadcast(a,{t:"notice",text:"Wall contest released"});}
  }
}
function constrainPenaltyKeeper(a){const s=a.shootout;if(!s||s.gkSlot==null)return;const keeper=a.world.players[s.gkSlot],q=keeper.body.getPosition(),v=keeper.body.getLinearVelocity(),minY=MODE.GOAL_MIN_Y+MODE.PENALTY_GK_Y_MARGIN,maxY=MODE.GOAL_MAX_Y-MODE.PENALTY_GK_Y_MARGIN,x=Math.max(MODE.PENALTY_GK_MIN_X,Math.min(MODE.PENALTY_GK_MAX_X,q.x)),y=Math.max(minY,Math.min(maxY,q.y)),eps=.025,vx=x<=MODE.PENALTY_GK_MIN_X+eps&&v.x<0||x>=MODE.PENALTY_GK_MAX_X-eps&&v.x>0?0:v.x,vy=y<=minY+eps&&v.y<0||y>=maxY-eps&&v.y>0?0:v.y;if(x!==q.x||y!==q.y)keeper.body.setTransform(new planck.Vec2(x,y),keeper.body.getAngle());if(vx!==v.x||vy!==v.y)keeper.body.setLinearVelocity(new planck.Vec2(vx,vy));}
function step(a){const n=now(),w=a.world,referenceTickScale=MODE.PHYSICS_REFERENCE_HZ/MODE.PHYSICS_HZ;if(a.phase==="waiting"&&a.players.size){begin(a);return;}if(a.phase==="countdown"&&n>=a.phaseUntil){a.phase="playing";a.clockLastAt=n;}if(a.phase==="goalCelebration"&&n>=a.phaseUntil){a.phase="goalReplay";a.phaseUntil=n+MODE.GOAL_REPLAY_SECONDS*1000;if(a.pendingGoalReplay)broadcast(a,a.pendingGoalReplay);}if(a.phase==="goalReplay"&&n>=a.phaseUntil){resetPositions(a);a.phase="countdown";a.phaseUntil=n+MODE.COUNTDOWN_MS;a.clockLastAt=a.phaseUntil;a.startedAt+=MODE.GOAL_CELEBRATION_MS+MODE.GOAL_REPLAY_SECONDS*1000+MODE.COUNTDOWN_MS;}if(a.phase==="penaltyCountdown"&&n>=a.phaseUntil){a.phase="penalty";a.phaseUntil=n+MODE.PENALTY_SHOT_MS;broadcast(a,{t:"notice",text:"Penalty — shoot!"});}if(a.phase==="penaltyPause"&&n>=a.phaseUntil){startPenaltyShot(a);return;}if(a.phase==="ended"){if(n>=a.phaseUntil||a.votes.size>=Math.max(1,a.players.size))finalizeRematch(a);return;}if(a.phase==="playing"){if(!a.setPiece)a.clockRemainingMs=Math.max(0,a.clockRemainingMs-Math.max(0,n-(a.clockLastAt||n)));a.clockLastAt=n;}const penaltyPhase=a.phase==="penalty",celebrationPhase=a.phase==="goalCelebration";if(a.phase!=="playing"&&!penaltyPhase&&!celebrationPhase)return;if(penaltyPhase)constrainPenaltyKeeper(a);
  if(!celebrationPhase){enforceDefensiveFifths(a);enforceGoalKickClearance(a);updateStallSafety(a,n);manageSetPiece(a,n);}
  for(const [slot] of a.players){
    const p=w.players[slot],i=p.input,body=p.body,velocity=body.getLinearVelocity(),inputLength=Math.hypot(i.x,i.y),aim=inputLength?Math.atan2(i.y,i.x):body.getAngle(),boosting=!!(i.boost&&!i.brake&&inputLength&&(a.rules.unlimitedBoost||p.energy>=MODE.BOOST_DRAIN_PER_TICK));
    if(i.brake){
      body.applyLinearImpulse(velocity.clone().mul(-MODE.PLAYER_BRAKE_STRENGTH*1.5*referenceTickScale),body.getPosition(),true);
    }else if(inputLength){
      const velocityAngle=Math.atan2(velocity.y,velocity.x),delta=angleDifference(aim,velocityAngle),correction=MODE.PLAYER_STEERING_CORRECTION,isPenaltyKeeper=penaltyPhase&&slot===a.shootout?.gkSlot;
      const movementAngle=isPenaltyKeeper?aim:delta>0?(delta<Math.PI/2?aim+correction*angleDifference(velocityAngle,aim):aim-correction*angleDifference(velocityAngle+Math.PI,aim)):(delta>-Math.PI/2?aim+correction*angleDifference(velocityAngle,aim):aim-correction*angleDifference(velocityAngle+Math.PI,aim));
      const boostMultiplier=boosting?MODE.BOOST_MULTIPLIER:1,impulse=MODE.ACCELERATION/MODE.PHYSICS_HZ*1.5*a.rules.playerSpeed,thrust=new planck.Vec2(Math.cos(movementAngle)*impulse*boostMultiplier,Math.sin(movementAngle)*impulse*boostMultiplier),maxSpeed=MODE.MAX_SPEED*boostMultiplier*a.rules.playerSpeed;
      if(velocity.length()>maxSpeed)body.applyLinearImpulse(velocity.clone().mul(-MODE.PLAYER_OVERSPEED_RESISTANCE*impulse*a.rules.boostDeceleration),body.getPosition(),true);
      const proposed=thrust.clone().add(velocity);
      if(proposed.length()<=maxSpeed||proposed.length()<velocity.length())body.applyLinearImpulse(thrust,body.getPosition(),true);else{proposed.normalize();proposed.mul(velocity.length());proposed.sub(velocity);body.applyLinearImpulse(proposed,body.getPosition(),true);}
    }else if(velocity.length()>.01)body.applyLinearImpulse(velocity.clone().mul(-MODE.PLAYER_COAST_DRAG*referenceTickScale),body.getPosition(),true);
    if(inputLength){const turn=angleDifference(body.getAngle(),aim),turnLimit=MODE.PLAYER_TURN_RADIANS_PER_TICK*referenceTickScale;body.setTransform(body.getPosition(),body.getAngle()+Math.max(-turnLimit,Math.min(turnLimit,turn)));}
    if(a.rules.unlimitedBoost||(penaltyPhase&&p.body.isActive())||(celebrationPhase&&slot%2===a.pendingGoalReplay?.team))p.energy=100;else if(boosting)p.energy=Math.max(0,p.energy-MODE.BOOST_DRAIN_PER_TICK);else if(!i.boost||i.brake)p.energy=Math.min(100,p.energy+a.rules.boostRegenPerSecond/MODE.PHYSICS_HZ);
  }
  if(!penaltyPhase)for(const pad of w.boosts){if(!pad.active&&n>=pad.at)pad.active=true;if(pad.active)for(const [slot] of a.players){const p=w.players[slot],q=p.body.getPosition();if(Math.hypot(q.x-pad.x,q.y-pad.y)<=MODE.BOOST_PAD_PICKUP_DISTANCE){p.energy=Math.min(100,p.energy+a.rules.boostPadRefill);pad.active=false;pad.at=n+MODE.BOOST_RESPAWN_MS;break;}}}w.physics.step(1/MODE.PHYSICS_HZ);w.tick++;const ballPosition=w.ball.getPosition(),ballSpeed=w.ball.getLinearVelocity().length();for(let ballIndex=0;ballIndex<a.activeBallCount;ballIndex++){const ball=w.balls[ballIndex],bp=ball.getPosition(),speed=ball.getLinearVelocity().length(),current=new Set(),history=a.ballTouchHistory[ballIndex];for(const [slot] of a.players){const player=w.players[slot],q=player.body.getPosition();if(!player.body.isActive()||Math.hypot(q.x-bp.x,q.y-bp.y)>MODE.PLAYER_RADIUS+MODE.BALL_RADIUS+.3)continue;current.add(slot);a.ballTouches[ballIndex]=slot;if(ballIndex===0)a.lastBallTouchSlot=slot;const last=history.at(-1);if(last?.slot===slot){last.speed=Math.max(last.speed,speed);last.tick=w.tick;}else{history.push({slot,speed,tick:w.tick});if(history.length>12)history.shift();}}a.ballContactSlots[ballIndex]=current;if(ballIndex===0)a.touchHistory=history;}if(penaltyPhase&&a.shootout){const s=a.shootout,shooter=w.players[s.shooterSlot],shooterPosition=shooter.body.getPosition(),shooterVelocity=shooter.body.getLinearVelocity();if(shooterPosition.x>MODE.PENALTY_TAKER_MAX_X){shooter.body.setTransform(new planck.Vec2(MODE.PENALTY_TAKER_MAX_X,shooterPosition.y),shooter.body.getAngle());shooter.body.setLinearVelocity(new planck.Vec2(Math.min(0,shooterVelocity.x),shooterVelocity.y));}constrainPenaltyKeeper(a);const touchDistance=MODE.PLAYER_RADIUS+MODE.BALL_RADIUS+.3,distance=Math.hypot(shooter.body.getPosition().x-ballPosition.x,shooter.body.getPosition().y-ballPosition.y),touching=distance<=touchDistance;if(!touching&&distance>touchDistance+.08)s.shooterTouching=false;if(touching&&!s.shooterTouching){s.shooterTouching=true;if(s.ballTouched){broadcast(a,{t:"notice",text:"Double touch — penalty missed"});resolvePenalty(a,false);return;}s.ballTouched=true;const v=w.ball.getLinearVelocity();v.mul(MODE.PENALTY_BALL_SPEED_MULTIPLIER);w.ball.setLinearVelocity(v);}}
  const bp=w.ball.getPosition();if(penaltyPhase){const s=a.shootout;if(bp.x>MODE.GOAL_LINE_RIGHT_X&&bp.y>MODE.GOAL_MIN_Y&&bp.y<MODE.GOAL_MAX_Y)resolvePenalty(a,true);else{if(bp.x>MODE.PENALTY_BOX_LINE_X+MODE.PENALTY_EXIT_HYSTERESIS)s.enteredBox=true;if((s.enteredBox&&bp.x<MODE.PENALTY_BOX_LINE_X-MODE.PENALTY_EXIT_HYSTERESIS)||n>=a.phaseUntil)resolvePenalty(a,false);}return;}if(celebrationPhase)return;for(let index=0;index<a.activeBallCount;index++){const q=w.balls[index].getPosition();if(q.y>MODE.GOAL_MIN_Y&&q.y<MODE.GOAL_MAX_Y){if(q.x<MODE.GOAL_LINE_LEFT_X){score(a,1,index);break;}if(q.x>MODE.GOAL_LINE_RIGHT_X){score(a,0,index);break;}}}if(a.clockRemainingMs<=0){if(w.score[0]===w.score[1])beginShootout(a);else finish(a);}
}
function replayData(a){return {format:"NC11-REPLAY",version:2,mode:MODE,boostPads:BOOST_PAD_LAYOUT,arena:a.id,created:new Date().toISOString(),players:[...a.players].map(([slot,c])=>[slot,c.name]),finalScore:[...a.world.score],durationMs:a.replay.at(-1)?.replayMs||0,events:a.events,frames:a.replay};}
function welcome(c){send(c,{t:"welcome",protocol:MODE.PROTOCOL,mode:MODE,boostPads:BOOST_PAD_LAYOUT,role:c.role,slot:c.slot??null,arena:c.arena?.id,party:c.arena?.party||null,host:c.arena?.hostId===c.id,meowEnabled:c.arena?.meowEnabled!==false,quickChatSet:c.arena?.quickChatSet||"custom"});send(c,{t:"rules",rules:publicRules(c.arena)});send(c,{t:"art",mime:"image/png",data:PITCH_ART_BASE64});send(c,{t:"cleanArt",mime:"image/png",data:PAD_FREE_PITCH_ART_BASE64});send(c,{t:"padArt",mime:"image/png",data:BOOST_PAD_HOUSING_BASE64});send(c,{t:"eventAssets",imageMime:"image/png",imageData:RANDOM_EVENT_IMAGE_BASE64,audioMime:"audio/mpeg",audioData:RANDOM_EVENT_AUDIO_BASE64});if(c.arena)send(c,snapshot(c.arena));}
function parseUrl(req){return new URL(req.url,"http://127.0.0.1");}
function join(c,u){const role=u.searchParams.get("role")==="spectator"?"spectator":"player",party=(u.searchParams.get("party")||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6),target=Number(u.searchParams.get("arena")||0);c.name=cleanName(u.searchParams.get("name"));c.id=(u.searchParams.get("clientId")||crypto.randomUUID()).slice(0,80);c.role=role;c.last=now();c.lastGameplayInput=c.last;let a;if(party)a=parties.get(party)||makeArena("private",party);else if(role==="spectator")a=(target?arenas.get(target):[...arenas.values()].find(x=>x.kind==="public"&&x.phase!=="retired"))||makeArena();else a=publicArena(target);if(!a||a.phase==="retired"){send(c,{t:"error",text:"That match is unavailable"});return false;}if(party&&!a.hostId)a.hostId=c.id;if(role==="spectator"){if(a.spectators.size>=MODE.SPECTATOR_CAPACITY){send(c,{t:"error",text:"Spectator capacity reached"});return false;}c.arena=a;c.slot=null;a.spectators.add(c);}else{const saved=reconnects.get(c.id),canRestore=saved?.expires>now()&&saved.arena===a.id&&!a.players.has(saved.slot)&&savedSlotKeepsBalance(a,saved.slot),slot=canRestore?saved.slot:pickSlot(a);if(slot===null){send(c,{t:"error",text:"Match is full"});return false;}activate(a,c,slot);if(a.shootout&&a.phase!=="ended"){const p=a.world.players[slot];p.input={x:0,y:0,boost:false,brake:false};p.body.setLinearVelocity(new planck.Vec2());p.body.setActive(false);p.body.setTransform(new planck.Vec2(-100,-100),0);}reconnects.delete(c.id);}welcome(c);if(a.phase==="ended")send(c,{t:"ended",score:a.world.score,shootout:a.shootout?{score:[...a.shootout.score],results:a.shootout.results.map(x=>[...x]),winner:a.shootout.winner}:null,replayReady:true,deadlineMs:Math.max(0,a.phaseUntil-now())});broadcast(a,{t:"roster",names:[...a.players].map(([slot,x])=>[slot,x.name]),spaces:openSlots(a).length});broadcast(a,{t:"system",text:role==="spectator"?`${c.name} is spectating!`:`${c.name} joined`});broadcastBalance(a);return true;}
function adminState(c){const a=c.arena;send(c,{t:"adminState",rules:publicRules(a),defaults:DEFAULT_RULES,currentRemaining:a.phase==="waiting"?a.rules.matchSecondsNext:Math.max(0,Math.ceil(a.clockRemainingMs/1000)),phase:a.phase,arena:a.id,meowEnabled:a.meowEnabled,quickChatSet:a.quickChatSet});}
function handleAdminMessage(c,m){
  if(!["adminLogin","adminSet","adminCurrentTime","adminGoPens","adminStateRequest","setMeow","setQuickChat"].includes(m.t))return false;
  const a=c.arena,fail=text=>send(c,{t:"adminError",text});
  if(m.t==="adminLogin"){
    if(!ADMIN_PASSWORD)return fail("Admin login is not configured on this server."),true;
    const address=c.socket.remoteAddress||"unknown",record=adminFailures.get(address)||{count:0,until:0};
    if(record.until>now())return fail("Too many attempts. Try again later."),true;
    const supplied=String(m.password||"").slice(0,200),hash=value=>crypto.createHash("sha256").update(value).digest();
    if(crypto.timingSafeEqual(hash(supplied),hash(ADMIN_PASSWORD))){c.admin=true;adminFailures.delete(address);send(c,{t:"adminLoginResult",ok:true});adminState(c);}
    else{record.count++;if(record.count>=5){record.count=0;record.until=now()+300000;}adminFailures.set(address,record);fail("Incorrect admin password.");}
    return true;
  }
  if(!c.admin)return fail("Admin login required."),true;
  if(m.t==="adminStateRequest"){adminState(c);return true;}
  if(m.t==="setMeow"){a.meowEnabled=!!m.enabled;broadcast(a,{t:"meowSetting",enabled:a.meowEnabled});adminState(c);return true;}
  if(m.t==="setQuickChat"){a.quickChatSet=m.set==="default"?"default":"custom";broadcast(a,{t:"quickChatSetting",set:a.quickChatSet});adminState(c);return true;}
  if(m.t==="adminSet"){
    try{const previous=a.rules,next=sanitizedRules(previous,m.rules);a.rules=next;if(previous.barrierEnabled!==next.barrierEnabled||previous.barrierLimit!==next.barrierLimit||previous.barrierDepth!==next.barrierDepth)a.defensiveOrders=[new Map(),new Map()];if(previous.ballSpeed!==next.ballSpeed)setBallLightness(a);if(previous.ballCount!==next.ballCount)syncActiveBalls(a);if(!next.cornersEnabled&&a.setPiece?.type==="corner"){releaseCornerTaker(a,a.setPiece);a.setPiece=null;broadcast(a,{t:"restart",active:false});}broadcast(a,{t:"rules",rules:publicRules(a)});adminState(c);}
    catch(error){fail(error.message);}return true;
  }
  if(m.t==="adminCurrentTime"){
    const seconds=Number(m.seconds);if(a.phase!=="playing")fail("Current match time can only be changed during live play.");
    else if(!Number.isFinite(seconds)||seconds<0||seconds>1200)fail("Time must be 0–1200 seconds.");
    else{const remaining=Math.min(a.matchDurationSeconds,seconds);a.clockRemainingMs=remaining*1000;a.clockLastAt=now();a.startedAt=now()-(a.matchDurationSeconds-remaining)*1000;adminState(c);}return true;
  }
  if(m.t==="adminGoPens"){
    if(!["playing","countdown"].includes(a.phase)||!teamCounts(a).every(Boolean))fail("Both teams must have a player in an active match.");
    else{beginShootout(a);adminState(c);}return true;
  }
  return true;
}
function message(c,m){c.last=now();if(handleAdminMessage(c,m))return;const a=c.arena;if(!a)return;if(m.t==="testBallProps"&&process.env.NC11_TESTING==="1"){const ball=a.world.balls[Math.max(0,Math.min(a.activeBallCount-1,Math.trunc(Number(m.index)||0)))],fixture=ball.getFixtureList();send(c,{t:"testBallProps",mass:ball.getMass(),density:fixture.getDensity(),radius:fixture.getShape().m_radius,activeBalls:a.activeBallCount});return;}if(m.t==="input"&&c.role==="player"){const p=a.world.players[c.slot],x=Number(m.x)||0,y=Number(m.y)||0,boost=!!m.boost,brake=!!m.brake;p.input={x,y,boost,brake};if(x||y||boost||brake)c.lastGameplayInput=c.last;}else if(m.t==="ping")send(c,{t:"pong",n:m.n});else if(m.t==="latency")c.ping=Math.max(0,Math.min(9999,Math.round(Number(m.ms)||0)));else if(m.t==="chat"){const text=String(m.text||"").trim().slice(0,540),team=!!m.team&&c.role==="player";if(text){const event={t:"chat",slot:c.slot,name:c.name,spectator:c.role!=="player",team,text};team?broadcastTeam(a,c.slot%2,event):broadcast(a,event);}}else if(m.t==="switchTeam"&&c.role==="player")switchTeam(a,c);else if(m.t==="joinOffer"&&c.role==="spectator")send(c,{t:"joinOffer",arena:a.id,spaces:openSlots(a).length});else if(m.t==="replay")send(c,{t:"replay",data:replayData(a)});else if(m.t==="testVelocity"&&process.env.NC11_TESTING==="1"&&c.role==="player"){const p=a.world.players[c.slot];p.body.setTransform(new planck.Vec2(MODE.FIELD_WIDTH/2,MODE.FIELD_HEIGHT/2-8),0);p.body.setLinearVelocity(new planck.Vec2(Number(m.vx)||0,Number(m.vy)||0));}else if(m.t==="testBallVelocity"&&process.env.NC11_TESTING==="1"){a.world.ball.setTransform(new planck.Vec2(MODE.FIELD_WIDTH/2,MODE.FIELD_HEIGHT/2),0);a.world.ball.setLinearVelocity(new planck.Vec2(Number(m.vx)||0,Number(m.vy)||0));}else if(m.t==="testBallPosition"&&process.env.NC11_TESTING==="1"){const ball=a.world.balls[Math.max(0,Math.min(a.activeBallCount-1,Math.trunc(Number(m.index)||0)))];ball.setTransform(new planck.Vec2(Number(m.x)||0,Number(m.y)||0),0);ball.setLinearVelocity(new planck.Vec2(Number(m.vx)||0,Number(m.vy)||0));}else if(m.t==="testPadState"&&process.env.NC11_TESTING==="1"){const pad=a.world.boosts[Math.max(0,Math.min(a.world.boosts.length-1,Math.trunc(Number(m.index)||0)))];pad.active=!!m.active;pad.at=pad.active?0:now()+60000;}else if(m.t==="testBeginShootout"&&process.env.NC11_TESTING==="1")beginShootout(a);else if(m.t==="testPenaltyResult"&&process.env.NC11_TESTING==="1")resolvePenalty(a,!!m.goal);else if(m.t==="testEnd"&&process.env.NC11_TESTING==="1")finish(a);else if(m.t==="rematch"&&c.role==="player"&&a.phase==="ended"){const choice=m.choice==="shuffle"?"shuffle":"same";a.votes.set(c.id,choice);let same=0,shuffle=0;for(const vote of a.votes.values())vote==="shuffle"?shuffle++:same++;broadcast(a,{t:"rematch",votes:a.votes.size,needed:a.players.size,same,shuffle});}}
function cleanup(c,{reconnect=true,notice=`${c.name} left`}={}){if(c.cleaned)return;c.cleaned=true;const a=c.arena;if(!a)return;if(c.role==="player"&&a.players.get(c.slot)===c){a.players.delete(c.slot);if(reconnect)reconnects.set(c.id,{arena:a.id,slot:c.slot,expires:now()+MODE.RECONNECT_MS});else reconnects.delete(c.id);park(a,c.slot);}else a.spectators.delete(c);a.lastUsed=now();broadcast(a,{t:"roster",names:[...a.players].map(([slot,x])=>[slot,x.name]),spaces:openSlots(a).length});broadcast(a,{t:"system",text:notice});broadcastBalance(a);}
function upgrade(req,socket){if(req.headers.upgrade?.toLowerCase()!=="websocket")return socket.destroy();const key=req.headers["sec-websocket-key"],accept=crypto.createHash("sha1").update(key+"258EAFA5-E914-47DA-95CA-C5AB0DC85B11").digest("base64");socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`);const c={socket,pending:Buffer.alloc(0),cleaned:false};if(!join(c,parseUrl(req)))return setTimeout(()=>socket.end(),100);socket.on("data",chunk=>{try{for(const f of frames(c,chunk)){if(f.op===8){cleanup(c);socket.end(frame(Buffer.alloc(0),8));return;}if(f.op===9){socket.write(frame(f.p,10));continue;}if(f.op===1)message(c,JSON.parse(f.p.toString("utf8")));}}catch{socket.destroy();}});socket.on("close",()=>cleanup(c));socket.on("error",()=>cleanup(c));}

const server=http.createServer((req,res)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Content-Type","application/json");if(req.url==="/health")return res.end(JSON.stringify({ok:true,mode:MODE.ID,arenas:arenas.size,players:[...arenas.values()].reduce((n,a)=>n+a.players.size,0)}));const arena=[...arenas.values()][0];if(process.env.NC11_TESTING==="1"&&arena&&req.url==="/test/setup-corner"){const slots=[...arena.players.keys()];for(const [index,slot] of slots.slice(0,2).entries()){const p=arena.world.players[slot];p.body.setTransform(new planck.Vec2(24+index*2,75),0);p.body.setLinearVelocity(new planck.Vec2());p.input={x:0,y:0,boost:false,brake:false};}arena.world.ball.setTransform(new planck.Vec2(25.5,70),0);arena.world.ball.setLinearVelocity(new planck.Vec2());return res.end(JSON.stringify({ok:true}));}if(process.env.NC11_TESTING==="1"&&arena&&req.url==="/test/setup-wall"){const slots=[...arena.players.keys()];for(const [index,slot] of slots.slice(0,2).entries()){const p=arena.world.players[slot];p.body.setTransform(new planck.Vec2(71.5+index*7,9.5),0);p.body.setLinearVelocity(new planck.Vec2());p.input={x:0,y:0,boost:false,brake:false};}arena.world.ball.setTransform(new planck.Vec2(75,3.5),0);arena.world.ball.setLinearVelocity(new planck.Vec2());return res.end(JSON.stringify({ok:true}));}if(process.env.NC11_TESTING==="1"&&arena&&req.url==="/test/setup-goal"){arena.setPiece=null;broadcast(arena,{t:"restart",active:false});const scorer=[...arena.players.keys()].find(slot=>slot%2===0)??null;arena.lastBallTouchSlot=scorer;arena.ballTouches[0]=scorer;arena.touchHistory=scorer==null?[]:[{slot:scorer,speed:8,tick:arena.world.tick}];arena.ballTouchHistory[0]=arena.touchHistory;arena.world.ball.setTransform(new planck.Vec2(137,MODE.FIELD_HEIGHT/2),0);arena.world.ball.setLinearVelocity(new planck.Vec2(8,0));return res.end(JSON.stringify({ok:true}));}res.statusCode=404;res.end(JSON.stringify({error:"not found"}));});server.on("upgrade",upgrade);
const PHYSICS_STEP_MS=1000/MODE.PHYSICS_HZ;
let physicsLast=performance.now(),physicsAccumulator=0;
function publishSnapshots(){const n=now();for(const a of arenas.values())if(a.players.size||a.spectators.size){enforceDefensiveFifths(a);enforceGoalKickClearance(a);finishSetPieceAfterStep(a);const s=snapshot(a);broadcast(a,s);const recordable=a.phase==="playing"||a.phase==="penaltyCountdown"||a.phase==="penalty"||a.phase==="penaltyPause";if(recordable){a.lastReplayAt=n;const r=a.setPiece;a.replay.push({...s,replayMs:Math.max(0,n-a.startedAt),restart:r?{active:true,type:r.type,team:r.team,x:r.x,y:r.y,ballIndex:r.ballIndex,radius:MODE.CORNER_RADIUS,taker:r.taker}:null,rules:publicRules(a)});}}}
function playRandomEvent(a){if(!a.meowEnabled){a.randomEventPlayed=true;return;}const candidates=[...a.players.values()];if(!candidates.length)return;const first=candidates.splice(Math.floor(Math.random()*candidates.length),1)[0],selected=[first];if(candidates.length&&Math.random()<.5)selected.push(candidates[Math.floor(Math.random()*candidates.length)]);for(const c of selected)send(c,{t:"randomEvent",durationMs:1000});a.events.push({at:a.world.tick,replayMs:Math.max(0,now()-a.startedAt),type:"meow",slots:selected.map(c=>c.slot),durationMs:1000});a.randomEventPlayed=true;}
const physicsTimer=setInterval(()=>{const clock=performance.now(),elapsed=Math.max(0,clock-physicsLast);physicsLast=clock;physicsAccumulator=Math.min(physicsAccumulator+elapsed,PHYSICS_STEP_MS*MODE.MAX_PHYSICS_CATCHUP_STEPS);let stepped=false;while(physicsAccumulator>=PHYSICS_STEP_MS){for(const a of arenas.values())step(a);physicsAccumulator-=PHYSICS_STEP_MS;stepped=true;}if(stepped)publishSnapshots();const n=now();for(const a of arenas.values()){for(const c of [...a.players.values(),...a.spectators])if(n-c.last>MODE.IDLE_MS)c.socket.end();const inactivityMs=MODE.INACTIVITY_KICK_MS>0?MODE.INACTIVITY_KICK_MS:(a.kind==="public"?MODE.PUBLIC_INACTIVITY_KICK_MS:MODE.LOCAL_INACTIVITY_KICK_MS);for(const [slot,c] of [...a.players]){const q=a.world.players[slot].body.getPosition();if(c.inactivityPhase!==a.phase){c.inactivityPhase=a.phase;c.lastMovementAt=n;c.lastMovementX=q.x;c.lastMovementY=q.y;}if(Math.hypot(q.x-(c.lastMovementX??q.x),q.y-(c.lastMovementY??q.y))>=.08){c.lastMovementAt=n;c.lastMovementX=q.x;c.lastMovementY=q.y;}if(inactivityMs>0&&a.phase==="playing"&&n-c.lastMovementAt>=inactivityMs){send(c,{t:"returnHome",code:"inactivity",reason:"You have been kicked out for inactivity."});cleanup(c,{reconnect:false,notice:`${c.name} was kicked for inactivity`});c.socket.end();}}if(a.randomEventEligible&&!a.randomEventPlayed&&a.phase==="playing"&&n>=a.randomEventAt)playRandomEvent(a);if(!a.players.size&&!a.spectators.size&&n-a.lastUsed>30000){arenas.delete(a.id);if(a.party)parties.delete(a.party);}}for(const [id,r] of reconnects)if(r.expires<n)reconnects.delete(id);},4);
const messageBeforeExtendedChat=message;
message=function(c,m){if(m?.t!=="chat")return messageBeforeExtendedChat(c,m);c.last=now();const a=c.arena;if(!a)return;const text=String(m.text||"").trim().slice(0,540),team=!!m.team&&c.role==="player";if(text){const event={t:"chat",slot:c.slot,name:c.name,spectator:c.role!=="player",team,text};team?broadcastTeam(a,c.slot%2,event):broadcast(a,event);}};
server.listen(PORT,HOST,()=>console.log(`NitroClash local 11v11 listening on ws://${HOST}:${PORT}`));
export function closeServer(){clearInterval(physicsTimer);return new Promise(r=>server.close(r));}
