import assert from "node:assert/strict";
import fs from "node:fs";
import { spawn } from "node:child_process";
import { setTimeout as wait } from "node:timers/promises";

const cwd=new URL(".",import.meta.url).pathname.replace(/^\/(.:)/,"$1");
const serverSource=fs.readFileSync(new URL("server.mjs",import.meta.url),"utf8");
const child=spawn(process.execPath,["server.mjs"],{cwd,env:{...process.env,NC11_PORT:"18111",NC11_TESTING:"1",NC11_MATCH_SECONDS:"600",NC11_INACTIVITY_KICK_MS:"999999",NC11_POSTGAME_MS:"500",NC11_PENALTY_COUNTDOWN_MS:"60",NC11_PENALTY_SHOT_MS:"3000",NC11_PENALTY_PAUSE_MS:"100"},stdio:["ignore","pipe","pipe"]});
let output="";child.stdout.on("data",b=>output+=b);child.stderr.on("data",b=>output+=b);
async function ready(){for(let i=0;i<80;i++){if(child.exitCode!==null)throw new Error("server exited: "+output);try{const r=await fetch("http://127.0.0.1:18111/health",{signal:AbortSignal.timeout(100)});if(r.ok)return;}catch{}await wait(50);}throw new Error("server did not start: "+output);}
function connect(params={}){return new Promise((resolve,reject)=>{const q=new URLSearchParams({name:"Test",clientId:crypto.randomUUID(),...params}),ws=new WebSocket(`ws://127.0.0.1:18111/?${q}`),messages=[];const timer=setTimeout(()=>reject(new Error("connection timeout")),3000);ws.onmessage=e=>{const m=JSON.parse(e.data);messages.push(m);if(m.t==="welcome"||m.t==="error"){clearTimeout(timer);resolve({ws,m,messages,next:(type,timeout=3000)=>new Promise((res,rej)=>{const t=setTimeout(()=>rej(new Error("missing "+type)),timeout),fn=e=>{const x=JSON.parse(e.data);messages.push(x);if(x.t===type){clearTimeout(t);ws.removeEventListener("message",fn);res(x);}};ws.addEventListener("message",fn);})});}};ws.onerror=reject;});}
async function waitState(client,predicate,timeout=3000){const end=Date.now()+timeout;while(Date.now()<end){const state=client.messages.filter(m=>m.t==="state").at(-1);if(state&&predicate(state))return state;await wait(15);}throw new Error("state timeout");}
async function waitMessage(client,type,predicate=()=>true,timeout=3000){const end=Date.now()+timeout;while(Date.now()<end){const message=client.messages.find(m=>m.t===type&&predicate(m));if(message)return message;await wait(15);}throw new Error("message timeout: "+type);}

try{
  await ready();
  const players=[];
  for(let i=0;i<22;i++){
    const c=await connect({name:`P${i}`,team:"0",clientId:`player-${i}`});
    assert.equal(c.m.t,"welcome");assert.equal(c.m.protocol,38);assert.equal(c.m.mode.BUILD,"0.1.44");
    players.push(c);
  }
  const mode=players[0].m.mode;
  assert.equal(mode.PLAYER_SLOTS,22);assert.equal(mode.PLAYERS_PER_TEAM,11);assert.equal(mode.SPECTATOR_CAPACITY,32);
  assert.equal(mode.REGULATION_SECONDS,600);assert.equal(mode.MATCH_SECONDS,600);assert.equal(mode.LOCAL_INACTIVITY_KICK_MS,0);assert.equal(mode.PUBLIC_INACTIVITY_KICK_MS,20000);assert.equal(mode.INACTIVITY_KICK_MS,999999);assert.equal(mode.CORNER_STALL_MS,8000);assert.equal(mode.WALL_STALL_MS,10000);assert.match(serverSource,/Math\.min\(1200,Number\(process\.env\.NC11_MATCH_SECONDS \|\| 600\)\)/);assert.match(serverSource,/matchSecondsNext:\[30,1200\]/);
  assert.equal(mode.FIELD_WIDTH,150);assert.equal(mode.FIELD_HEIGHT,84.375);assert.equal(mode.NITROCLASH_MAP_SCALE,1.5);
  assert.equal(mode.GOAL_OPENING,14.0625);assert.equal(mode.GOAL_OPENING_MULTIPLIER,1.5);assert.equal(mode.GOAL_DEPTH,7.5);assert.equal(mode.GOAL_MAX_Y-mode.GOAL_MIN_Y,mode.GOAL_OPENING);
  assert.equal(mode.PLAYER_RADIUS,.6103515625);assert.equal(mode.BALL_RADIUS,1.068115234375);assert.equal(mode.BALL_VISUAL_RATIO_TO_PLAYER,1.75);
  assert.ok(Math.abs(mode.BALL_RADIUS/mode.PLAYER_RADIUS-1.75)<1e-12);
  const originalBallMass=mode.ORIGINAL_BALL_DENSITY*Math.PI*mode.ORIGINAL_BALL_RADIUS**2,currentBallMass=mode.BALL_DENSITY*Math.PI*mode.BALL_RADIUS**2;
  assert.ok(Math.abs(originalBallMass-currentBallMass)<1e-12,"larger ball preserves normal mass");
  assert.equal(mode.BALL_LINEAR_DAMPING,.25);assert.equal(mode.BALL_RESTITUTION,1);assert.equal(mode.BALL_FRICTION,.4);
  assert.equal(mode.PACE_MULTIPLIER,1.2);assert.equal(mode.MAX_SPEED,12);assert.equal(mode.ACCELERATION,.9);assert.equal(mode.BOOSTED_TOP_SPEED,24);
  assert.equal(mode.PHYSICS_REFERENCE_HZ,60);assert.equal(mode.PHYSICS_HZ,60);assert.equal(mode.SNAPSHOT_HZ,60);assert.equal(mode.REPLAY_HZ,60);assert.equal(mode.GOAL_REPLAY_SECONDS,6);assert.equal(mode.BOOST_DRAIN_RATE_MULTIPLIER,1.08);assert.equal(mode.BOOST_DRAIN_PER_SECOND,35.64);assert.equal(mode.BOOST_DRAIN_PER_TICK,.594);assert.equal(mode.BOOST_REGEN_PER_SECOND,.576);assert.equal(mode.BOOST_REGEN_PER_TICK,.0096);
  assert.match(serverSource,/p\.energy>=MODE\.BOOST_DRAIN_PER_TICK/,"a partial regen amount cannot activate a full boost tick");assert.match(serverSource,/i\.boost&&!i\.brake/,"braking prevents boost drain even while boost is held");assert.match(serverSource,/referenceTickScale=MODE\.PHYSICS_REFERENCE_HZ\/MODE\.PHYSICS_HZ/,"controller forces preserve their 60 Hz per-second behaviour");
  assert.equal(mode.PLAYER_COAST_DRAG,.00075);
  assert.equal(mode.BOOST_PAD_VISIBLE_TARGET_RATIO,1.45);assert.equal(mode.BOOST_PAD_ART_RADIUS,1.25);assert.equal(mode.BOOST_PAD_RADIUS,1.25);assert.equal(mode.BOOST_PAD_HOUSING_SOURCE_PIXELS,128);assert.equal(mode.PITCH_ART_SOURCE_WIDTH,4096);assert.equal(mode.BOOST_PAD_HOUSING_IMAGE_RADIUS,2);assert.equal(mode.BOOST_PAD_HOUSING_OPACITY,1);assert.equal(mode.STOCK_BOOST_PAD_COUNT,14);assert.equal(mode.EXTRA_BOOST_PAD_COUNT,8);assert.equal(mode.TOTAL_BOOST_PAD_COUNT,22);
  const layout=players[0].m.boostPads,key=([x,y])=>`${x.toFixed(4)},${y.toFixed(4)}`,keys=new Set(layout.map(key));assert.equal(layout.length,22);
  for(const [x,y] of layout){assert.ok(keys.has(key([mode.FIELD_WIDTH-x,y])),`missing horizontal mirror for ${x},${y}`);assert.ok(keys.has(key([x,mode.FIELD_HEIGHT-y])),`missing vertical mirror for ${x},${y}`);}
  const closest=Math.min(...layout.flatMap((a,i)=>layout.slice(i+1).map(b=>Math.hypot(a[0]-b[0],a[1]-b[1]))));assert.ok(closest>10,`pads must not form crowded clusters (${closest})`);
  assert.deepEqual(layout.slice(-4),[[31.5,42.1875],[118.5,42.1875],[75,21.09375],[75,63.28125]]);
  assert.equal(mode.PENALTY_INITIAL_ROUNDS,5);assert.equal(mode.PENALTY_BOX_LINE_X,116.8945);assert.equal(mode.PENALTY_BALL_X,116.8945);assert.equal(mode.PENALTY_TAKER_X,98.75);assert.equal(mode.PENALTY_BALL_SPEED_MULTIPLIER,1.4);assert.equal(mode.PENALTY_SHOT_MS,3000);assert.equal(mode.PENALTY_UNLIMITED_BOOST,true);
  assert.equal("BALL_HIT_SPEED_MULTIPLIER" in mode,false);assert.equal("BALL_MAX_SPEED" in mode,false);
  assert.deepEqual(players.map(c=>c.m.slot),Array.from({length:22},(_,i)=>i),"forced team query is ignored and joins auto-balance");
  const arena=players[0].m.arena;assert.ok(players.every(c=>c.m.arena===arena));
  const full=await connect({arena:String(arena),clientId:"full-target"});assert.equal(full.m.t,"error");full.ws.close();
  const routingA=await connect({clientId:"routing-a",name:"RoutingA"}),routingB=await connect({clientId:"routing-b",name:"RoutingB"});assert.notEqual(routingA.m.arena,arena,"a new public lobby is created only after the existing one reaches 22 players");assert.equal(routingB.m.arena,routingA.m.arena,"the next public player joins that same non-full lobby");
  const routingPenalty=routingA.next("penaltyStart");routingA.ws.send(JSON.stringify({t:"testBeginShootout"}));await routingPenalty;await waitState(routingA,s=>s.phase==="penalty");const routingLate=await connect({clientId:"routing-late",name:"RoutingLate"});assert.equal(routingLate.m.arena,routingA.m.arena,"Play 11v11 joins the existing public match during penalties");const latePenaltyState=await waitState(routingLate,s=>s.phase==="penalty");assert.equal(latePenaltyState.p[routingLate.m.slot][7],0,"a player joining during penalties reserves a place but cannot enter the shootout");const nextPenalty=routingA.next("penaltyStart");routingA.ws.send(JSON.stringify({t:"testPenaltyResult",goal:false}));const nextPick=await nextPenalty;assert.notEqual(nextPick.shooterSlot,routingLate.m.slot);assert.notEqual(nextPick.gkSlot,routingLate.m.slot);
  routingA.ws.send(JSON.stringify({t:"testEnd"}));await waitMessage(routingLate,"ended");const rematchJoin=await connect({clientId:"routing-rematch",name:"RoutingRematch"});assert.equal(rematchJoin.m.arena,routingA.m.arena,"Play 11v11 joins the existing public rematch lobby");await waitMessage(rematchJoin,"ended");for(const c of [routingA,routingB,routingLate,rematchJoin])c.ws.close();
  for(const [i,c] of players.entries())c.ws.send(JSON.stringify({t:"input",x:i%2?1:-1,y:0,boost:i%3===0}));
  await wait(4300);
  const live=players[0].messages.filter(m=>m.t==="state").at(-1);assert.equal(live.phase,"playing");assert.equal(live.b.length,6);assert.equal(live.p.filter(p=>p[7]).length,22);assert.equal(live.pads.length,22);assert.ok(players[0].messages.some(m=>m.t==="state"&&m.phase==="playing"&&m.p[0][9]===1),"boosting state is transmitted while boost remains");
  players[0].ws.send(JSON.stringify({t:"adminLogin",password:"Chicken999!"}));await waitMessage(players[0],"adminLoginResult",m=>m.ok);players[0].ws.send(JSON.stringify({t:"adminCurrentTime",seconds:121}));await waitMessage(players[0],"adminState",m=>m.currentRemaining===121);await waitState(players[0],s=>s.phase==="playing"&&s.clock===121);await wait(2200);const belowTwoMinutes=await waitState(players[0],s=>s.phase==="playing"&&s.clock<120);assert.ok(belowTwoMinutes.clock<120,"the live clock crosses below 2:00 instead of sticking there");
  const liveTicks=players[0].messages.filter(m=>m.t==="state"&&m.phase==="playing").slice(-60).map(m=>m.tick);assert.ok(liveTicks.length>20);assert.ok(liveTicks.every((tick,i)=>i===0||tick>liveTicks[i-1]),"playing snapshots are emitted only after a new authoritative physics step");
  assert.ok(players[0].messages.some(m=>m.t==="art"&&m.data.length>100000));assert.ok(players[0].messages.some(m=>m.t==="cleanArt"&&m.data.length>100000));assert.ok(players[0].messages.some(m=>m.t==="padArt"&&m.data.length>1000));

  const pace=await connect({party:"PACE19",clientId:"pace-probe",name:"Pace"});await wait(3100);
  pace.ws.send(JSON.stringify({t:"testVelocity",vx:0,vy:0}));pace.ws.send(JSON.stringify({t:"input",x:1,y:0,boost:false}));await wait(800);
  let paceState=pace.messages.filter(m=>m.t==="state").at(-1),paceSpeed=Math.hypot(paceState.p[pace.m.slot][4],paceState.p[pace.m.slot][5]);assert.ok(paceSpeed>=11&&paceSpeed<=13,`normal pace ${paceSpeed}`);
  pace.ws.send(JSON.stringify({t:"testVelocity",vx:0,vy:0}));pace.ws.send(JSON.stringify({t:"input",x:0,y:-1,boost:true}));await wait(800);
  paceState=pace.messages.filter(m=>m.t==="state").at(-1);paceSpeed=Math.hypot(paceState.p[pace.m.slot][4],paceState.p[pace.m.slot][5]);assert.ok(paceSpeed>=22&&paceSpeed<=26,`boost pace ${paceSpeed}`);const beforeBrakeAngle=paceState.p[pace.m.slot][3];pace.ws.send(JSON.stringify({t:"input",x:1,y:0,boost:true,brake:true}));await wait(100);const brakeEnergy=pace.messages.filter(m=>m.t==="state").at(-1).p[pace.m.slot][6];await wait(300);const braked=pace.messages.filter(m=>m.t==="state").at(-1).p[pace.m.slot];assert.ok(braked[6]>=brakeEnergy,"holding boost while braking does not consume boost");assert.equal(braked[9],1,"brake plus boost keeps the glow visible");assert.ok(Math.abs(braked[3]-beforeBrakeAngle)>.2,"braking still turns the player's facing direction toward the cursor");pace.ws.close();
  const coast=await connect({party:"COAST25",clientId:"coast-probe",name:"Coast"});await wait(3100);coast.ws.send(JSON.stringify({t:"testVelocity",vx:12,vy:0}));coast.ws.send(JSON.stringify({t:"input",x:0,y:0,boost:false}));await wait(1000);const coastState=coast.messages.filter(m=>m.t==="state").at(-1),coastSpeed=Math.hypot(coastState.p[coast.m.slot][4],coastState.p[coast.m.slot][5]);assert.ok(coastSpeed>4&&coastSpeed<8,`released input naturally loses speed instead of coasting forever (${coastSpeed})`);coast.ws.close();

  const impactStart=players[0].messages.length;players[3].ws.send(JSON.stringify({t:"testVelocity",vx:0,vy:30}));players[3].ws.send(JSON.stringify({t:"input",x:0,y:1,boost:false}));await wait(500);
  const peakBall=Math.max(...players[0].messages.slice(impactStart).filter(m=>m.t==="state").map(m=>Math.hypot(m.b[2],m.b[3])));assert.ok(peakBall>mode.BOOSTED_TOP_SPEED,`hard hit launches ball faster than boosted player (${peakBall} > ${mode.BOOSTED_TOP_SPEED})`);
  players[0].ws.send(JSON.stringify({t:"testBallVelocity",vx:30,vy:0}));await wait(1000);const coastBall=players[0].messages.filter(m=>m.t==="state").at(-1),coastBallSpeed=Math.hypot(coastBall.b[2],coastBall.b[3]);assert.ok(coastBallSpeed>20,`reduced damping keeps ball moving (${coastBallSpeed})`);

  const goalProbe=await connect({party:"GOAL23",clientId:"goal-probe",name:"GoalProbe"});await wait(3100);const goal=goalProbe.next("goal"),goalReplay=goalProbe.next("goalReplay",8000);goalProbe.ws.send(JSON.stringify({t:"testBallPosition",x:137.0,y:42.1875,vx:8,vy:0}));const goalEvent=await goal;assert.equal(goalEvent.team,0,"ball scores just inside the clean stock goal instead of requiring a deep net push");assert.equal(goalEvent.celebrationMs,5000);const celebration=await waitState(goalProbe,s=>s.phase==="goalCelebration");assert.equal(celebration.p[goalProbe.m.slot][6],100,"the scoring team receives unlimited celebration boost");const replayClip=await goalReplay;assert.equal(replayClip.durationMs,6000);assert.ok(replayClip.frames.length>0,"goal replay is queued after the celebration and includes recorded frames");assert.equal(replayClip.clipStartMs,replayClip.frames[0].replayMs);assert.equal(replayClip.clipEndMs,replayClip.frames.at(-1).replayMs);assert.ok(replayClip.frames.every((frame,index,array)=>index===0||frame.replayMs>=array[index-1].replayMs),"goal replay carries monotonic authoritative timestamps");goalProbe.ws.close();

  players[0].ws.close();players[2].ws.close();await wait(150);const imbalance=players[1].messages.filter(m=>m.t==="balance").at(-1);assert.equal(imbalance.fromTeam,1);assert.equal(imbalance.toTeam,0);assert.equal(imbalance.needed,1);
  const switched=players[1].next("slot");players[1].ws.send(JSON.stringify({t:"switchTeam"}));const slotMessage=await switched;assert.equal(slotMessage.slot%2,0,"first eligible volunteer moves to smaller team");
  await wait(100);const balanceCleared=players[3].messages.filter(m=>m.t==="balance").at(-1);assert.equal(balanceCleared.needed,0);

  const penaltyBlue=await connect({party:"PEN019",clientId:"penalty-blue",name:"BlueTaker"}),penaltyRed=await connect({party:"PEN019",clientId:"penalty-red",name:"RedKeeper"});
  const firstPenalty=penaltyBlue.next("penaltyStart");penaltyBlue.ws.send(JSON.stringify({t:"testBeginShootout"}));const opening=await firstPenalty;assert.equal(opening.team,0);assert.equal(opening.shooterSlot%2,0);assert.equal(opening.gkSlot%2,1);
  let penaltyState=await waitState(penaltyBlue,s=>s.phase==="penalty");assert.equal(penaltyState.penalty.shotMs>0,true);assert.equal(penaltyState.p.filter(p=>p[7]).length,2);assert.ok(Math.abs(penaltyState.p[opening.shooterSlot][1]-mode.PENALTY_TAKER_X)<.01);assert.ok(Math.abs(penaltyState.b[0]-mode.PENALTY_BALL_X)<.01,"penalty ball starts on the box line");
  penaltyBlue.ws.send(JSON.stringify({t:"input",x:0,y:0,boost:false}));penaltyRed.ws.send(JSON.stringify({t:"input",x:0,y:1,boost:true}));await wait(900);penaltyState=penaltyBlue.messages.filter(m=>m.t==="state").at(-1);const shooter=penaltyState.p[opening.shooterSlot],keeper=penaltyState.p[opening.gkSlot],keeperMaxY=mode.GOAL_MAX_Y-mode.PENALTY_GK_Y_MARGIN;assert.equal(shooter[6],100,"penalty taker has unlimited boost");assert.equal(keeper[6],100,"penalty goalkeeper has unlimited boost");assert.ok(keeper[1]>=mode.PENALTY_GK_MIN_X-.002&&keeper[1]<=mode.PENALTY_GK_MAX_X+.002);assert.ok(keeper[2]>=mode.GOAL_MIN_Y+mode.PENALTY_GK_Y_MARGIN-.002&&keeper[2]<=keeperMaxY+.002);assert.ok(keeper[2]>keeperMaxY-.15,"goalkeeper reaches the edge of the allowed area");penaltyRed.ws.send(JSON.stringify({t:"input",x:0,y:-1,boost:true}));await wait(250);const reversedKeeper=penaltyBlue.messages.filter(m=>m.t==="state").at(-1).p[opening.gkSlot];assert.ok(reversedKeeper[2]<keeperMaxY-.2,"goalkeeper moves inward immediately after turning at the boundary");
  const boxExitMiss=penaltyBlue.next("penaltyResult");penaltyBlue.ws.send(JSON.stringify({t:"testBallPosition",x:117.7,y:42.1875,vx:0,vy:0}));await wait(60);penaltyBlue.ws.send(JSON.stringify({t:"testBallPosition",x:115.8,y:42.1875,vx:-1,vy:0}));assert.equal((await boxExitMiss).goal,false,"a shot that enters the box and comes back out is immediately over");
  const results=[false,true,false,true,false,true];let shootoutEndPromise;await waitState(penaltyBlue,s=>s.phase==="penaltyPause");
  for(let i=0;i<results.length;i++){await waitState(penaltyBlue,s=>s.phase==="penalty");if(i===results.length-1)shootoutEndPromise=penaltyBlue.next("ended");penaltyBlue.ws.send(JSON.stringify({t:"testPenaltyResult",goal:results[i]}));if(i<results.length-1)await waitState(penaltyBlue,s=>s.phase==="penaltyPause");}
  const shootoutEnd=await shootoutEndPromise;assert.deepEqual(shootoutEnd.shootout.score,[3,0]);assert.equal(shootoutEnd.shootout.winner,0);
  const selections=penaltyBlue.messages.filter(m=>m.t==="penaltyStart");assert.ok(selections.length>=7);for(const pick of selections){assert.equal(pick.shooterSlot%2,pick.team,"penalty taker remains on their existing team");assert.equal(pick.gkSlot%2,1-pick.team,"goalkeeper remains on their existing team");}
  const penaltyReplayPromise=penaltyBlue.next("replay");penaltyBlue.ws.send(JSON.stringify({t:"replay"}));const penaltyReplay=await penaltyReplayPromise;assert.ok(penaltyReplay.data.events.some(e=>e.type==="penalty"));assert.ok(penaltyReplay.data.frames.some(f=>f.penalty));

  const spectator=await connect({role:"spectator",arena:String(arena),name:"Watcher",clientId:"watcher"});assert.equal(spectator.m.slot,null);await waitMessage(players[3],"system",m=>m.text==="Watcher is spectating!");spectator.ws.send(JSON.stringify({t:"ping",n:12345}));assert.equal((await spectator.next("pong")).n,12345);
  const chatPromise=players[3].next("chat");spectator.ws.send(JSON.stringify({t:"chat",text:"hello from spectator"}));assert.equal((await chatPromise).text,"hello from spectator");const longChat=players[3].next("chat");spectator.ws.send(JSON.stringify({t:"chat",text:"x".repeat(700)}));assert.equal((await longChat).text.length,540,"server enforces the extended chat limit");
  const replayPromise=spectator.next("replay");spectator.ws.send(JSON.stringify({t:"replay"}));const replay=await replayPromise;assert.equal(replay.data.format,"NC11-REPLAY");assert.equal(replay.data.mode.PLAYER_SLOTS,22);assert.equal(replay.data.mode.REPLAY_HZ,60);assert.ok(replay.data.frames.some((f,i,a)=>i>0&&f.replayMs-a[i-1].replayMs<25),"future downloads record near-60 Hz authoritative movement");

  const teamBlueA=await connect({party:"TEAM28",clientId:"team-blue-a",name:"BlueA"}),teamRed=await connect({party:"TEAM28",clientId:"team-red",name:"Red"}),teamBlueB=await connect({party:"TEAM28",clientId:"team-blue-b",name:"BlueB"});teamBlueA.ws.send(JSON.stringify({t:"chat",team:true,text:"blue only"}));await wait(300);assert.ok(teamBlueA.messages.some(m=>m.t==="chat"&&m.text==="blue only"&&m.team));assert.ok(teamBlueB.messages.some(m=>m.t==="chat"&&m.text==="blue only"&&m.team));assert.equal(teamRed.messages.some(m=>m.t==="chat"&&m.text==="blue only"),false,"team chat is not sent to opponents");

  const host=await connect({party:"REM019",clientId:"rematch-a",name:"A"}),guest=await connect({party:"REM019",clientId:"rematch-b",name:"B"});const hostEnded=host.next("ended"),guestEnded=guest.next("ended");host.ws.send(JSON.stringify({t:"testEnd"}));await Promise.all([hostEnded,guestEnded]);const hostResult=host.next("rematchResult"),guestResult=guest.next("rematchResult");host.ws.send(JSON.stringify({t:"rematch",choice:"same"}));guest.ws.send(JSON.stringify({t:"rematch",choice:"shuffle"}));assert.equal((await hostResult).choice,"same");assert.equal((await guestResult).choice,"same");

  const zone=[];for(let i=0;i<11;i++)zone.push(await connect({party:"FIFTH31",clientId:`fifth-${i}`,name:`F${i}`}));await wait(3100);for(const c of zone)if(c.m.slot%2===0)c.ws.send(JSON.stringify({t:"input",x:-1,y:0,boost:true}));await wait(6500);const zoneState=zone[0].messages.filter(m=>m.t==="state").at(-1),blueInside=zoneState.p.filter(p=>p[7]&&p[0]%2===0&&p[1]<=mode.DEFENSIVE_FIFTH_DEPTH);assert.equal(blueInside.length,mode.DEFENSIVE_FIFTH_LIMIT,"a sixth teammate can never enter the defensive fifth");for(const c of zone)c.ws.close();

  for(const c of [...players,pace,penaltyBlue,penaltyRed,spectator,teamBlueA,teamRed,teamBlueB,host,guest])try{c.ws.close();}catch{}
  console.log("PASS: v0.1.44 Frankfurt core rules, 8s corner timer, 10s throw-in timer, monotonic clock, spectator message, extended chat, braking and penalties");
} finally {child.kill();}
